-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mpc_fpga_top_opencl_fp_recip_fn is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (25 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (22 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of mpc_fpga_top_opencl_fp_recip_fn is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv6_3D : STD_LOGIC_VECTOR (5 downto 0) := "111101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_3B : STD_LOGIC_VECTOR (5 downto 0) := "111011";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_3A : STD_LOGIC_VECTOR (5 downto 0) := "111010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal recip_lut_fn_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal recip_lut_fn_q0 : STD_LOGIC_VECTOR (18 downto 0);
    signal recip_lut_fn_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal recip_lut_fn_q1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln804_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln804_reg_1887 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln804_reg_1887_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln804_reg_1887_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln804_reg_1887_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln804_reg_1887_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln804_reg_1887_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_fu_319_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_reg_1893 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_reg_1893_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_reg_1893_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_reg_1893_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_reg_1893_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_reg_1893_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal abs_raw_signed_2_fu_333_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal abs_raw_signed_2_reg_1898 : STD_LOGIC_VECTOR (25 downto 0);
    signal abs_raw_signed_2_reg_1898_pp0_iter1_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln819_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln819_reg_1936 : STD_LOGIC_VECTOR (0 downto 0);
    signal shift_fu_365_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shift_reg_1941 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln821_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_reg_1946 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln822_fu_387_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln822_reg_1951 : STD_LOGIC_VECTOR (5 downto 0);
    signal shift_4_fu_656_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal shift_4_reg_1956 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln221_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_1981 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_1981_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_1981_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_1981_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_reg_1981_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_1987 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_1987_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_1987_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_1987_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_1987_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_1_fu_676_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_1_reg_1993 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_1_reg_1993_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_1_reg_1993_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_1_reg_1993_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_1_reg_1993_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_1_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_1_reg_2000 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_1_reg_2000_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_1_reg_2000_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_1_reg_2000_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_1_reg_2000_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_2_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_2_reg_2006 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_2_reg_2006_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_2_reg_2006_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_2_reg_2006_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_2_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_2_reg_2012 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_2_reg_2012_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_2_reg_2012_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_2_reg_2012_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_3_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_3_reg_2017 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_3_reg_2017_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_3_reg_2017_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_3_reg_2017_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_3_fu_827_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_3_reg_2023 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_3_reg_2023_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_3_reg_2023_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_3_reg_2023_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_4_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_4_reg_2028 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_4_reg_2028_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_4_reg_2028_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_4_reg_2028_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_4_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_4_reg_2034 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_4_reg_2034_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_4_reg_2034_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_4_reg_2034_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_5_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_5_reg_2039 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_5_reg_2039_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_5_reg_2039_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_5_reg_2039_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_5_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_5_reg_2045 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_5_reg_2045_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_5_reg_2045_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_5_reg_2045_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_6_fu_943_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_6_reg_2050 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_6_reg_2050_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_6_reg_2050_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_6_reg_2050_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_6_fu_965_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_6_reg_2056 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_6_reg_2056_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_6_reg_2056_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_6_reg_2056_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_7_fu_989_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_7_reg_2061 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_7_reg_2061_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_7_reg_2061_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_7_reg_2061_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_7_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_7_reg_2067 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_7_reg_2067_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_7_reg_2067_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_7_reg_2067_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_8_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_8_reg_2072 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_8_reg_2072_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_8_reg_2072_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln221_8_reg_2072_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_8_fu_1057_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_8_reg_2078 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_8_reg_2078_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_8_reg_2078_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_8_reg_2078_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_9_fu_1081_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_9_reg_2083 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_9_reg_2083_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_9_reg_2083_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_9_reg_2083_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_10_fu_1105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_10_reg_2089 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_10_reg_2089_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_10_reg_2089_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_10_reg_2089_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_11_fu_1129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_11_reg_2094 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_11_reg_2094_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_11_reg_2094_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_11_reg_2094_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_12_fu_1153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_12_reg_2100 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_12_reg_2100_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_12_reg_2100_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_12_reg_2100_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_13_fu_1177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_13_reg_2105 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_13_reg_2105_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_13_reg_2105_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_13_reg_2105_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_14_fu_1201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_14_reg_2111 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_14_reg_2111_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_14_reg_2111_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_14_reg_2111_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_15_fu_1225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_15_reg_2116 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_15_reg_2116_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_15_reg_2116_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_15_reg_2116_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lut_idx_reg_2122 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln858_fu_1248_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln858_reg_2128 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln858_reg_2128_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln858_reg_2128_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v0_reg_2143 : STD_LOGIC_VECTOR (18 downto 0);
    signal v0_reg_2143_pp0_iter5_reg : STD_LOGIC_VECTOR (18 downto 0);
    signal v1_reg_2150 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln_reg_2155 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln859_fu_1255_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln860_fu_1265_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal recip_lut_fn_ce1_local : STD_LOGIC;
    signal recip_lut_fn_ce0_local : STD_LOGIC;
    signal abs_raw_signed_fu_327_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal clz_fu_341_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal clz_fu_341_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln816_fu_349_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal msb_fu_353_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_371_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal spec_select_fu_393_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal shift_1_fu_399_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_57_fu_461_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_472_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_59_fu_485_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_60_fu_498_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_61_fu_511_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_62_fu_524_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_63_fu_537_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_64_fu_550_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln829_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_7_fu_559_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_65_fu_563_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln829_1_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_6_fu_546_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_fu_572_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln829_2_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_5_fu_533_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_1_fu_580_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln829_3_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_4_fu_520_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_2_fu_588_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln829_4_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_3_fu_507_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_3_fu_596_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln829_5_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_2_fu_494_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_4_fu_604_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln829_6_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_1_fu_481_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_5_fu_612_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln829_7_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln834_fu_468_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_6_fu_620_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln829_7_fu_628_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln834_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shift_2_fu_642_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_56_fu_405_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shift_3_fu_648_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal shifted_63_fu_691_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln809_fu_688_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_fu_707_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal shifted_64_fu_710_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_49_fu_700_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_65_fu_725_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_50_fu_718_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_1_fu_741_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal shifted_66_fu_744_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_51_fu_734_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_67_fu_764_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_52_fu_752_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_2_fu_786_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal shifted_68_fu_789_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_53_fu_773_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_69_fu_810_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_54_fu_797_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_3_fu_832_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shifted_70_fu_835_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_55_fu_819_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_fu_856_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_fu_843_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_4_fu_878_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shifted_71_fu_881_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_56_fu_865_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_72_fu_902_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_57_fu_889_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_5_fu_924_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal shifted_73_fu_927_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_58_fu_911_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_74_fu_948_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_59_fu_935_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_6_fu_970_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shifted_75_fu_973_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_60_fu_957_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_76_fu_994_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_61_fu_981_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_7_fu_1016_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shifted_77_fu_1019_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_62_fu_1003_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shifted_78_fu_1040_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_63_fu_1027_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_8_fu_1062_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shifted_79_fu_1065_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_64_fu_1049_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_9_fu_1086_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shifted_80_fu_1089_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_65_fu_1073_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_10_fu_1110_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal shifted_81_fu_1113_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_66_fu_1097_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_11_fu_1134_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal shifted_82_fu_1137_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_67_fu_1121_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_12_fu_1158_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal shifted_83_fu_1161_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_68_fu_1145_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_13_fu_1182_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal shifted_84_fu_1185_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_69_fu_1169_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln224_14_fu_1206_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal shifted_85_fu_1209_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_70_fu_1193_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_71_fu_1217_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_norm_raw_72_fu_1230_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln848_fu_1252_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln860_fu_1259_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln862_fu_1270_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln862_fu_1281_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln862_fu_1281_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln862_1_fu_1300_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln859_1_fu_1297_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal est_raw_fu_1307_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_66_fu_1317_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal shifted_51_fu_1331_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_67_fu_1343_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_68_fu_1365_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln862_fu_1303_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_69_fu_1387_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln237_fu_1401_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_70_fu_1413_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln237_1_fu_1427_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_71_fu_1439_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln237_2_fu_1453_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_72_fu_1465_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln237_3_fu_1479_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_73_fu_1491_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln237_4_fu_1505_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_74_fu_1517_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln235_4_fu_1527_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_61_fu_1509_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln235_3_fu_1501_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_60_fu_1483_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln235_2_fu_1475_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_59_fu_1457_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln235_1_fu_1449_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_58_fu_1431_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln235_fu_1423_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_57_fu_1405_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_56_fu_1397_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_55_fu_1379_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_54_fu_1375_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_53_fu_1357_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_52_fu_1353_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln231_1_fu_1339_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_50_fu_1327_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln231_fu_1313_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_fu_1538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_fu_1531_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln236_1_fu_1542_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln236_1_fu_1549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_2_fu_1560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_2_fu_1553_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln236_3_fu_1564_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln236_14_fu_1684_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln236_3_fu_1571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_4_fu_1582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_4_fu_1575_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_5_fu_1586_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_5_fu_1593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_6_fu_1604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_6_fu_1597_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_7_fu_1608_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_7_fu_1615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_8_fu_1626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_8_fu_1619_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_9_fu_1630_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_9_fu_1637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_10_fu_1648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_10_fu_1641_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_11_fu_1652_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_11_fu_1659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_12_fu_1678_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_13_fu_1670_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln236_fu_1692_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln236_19_fu_1758_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln236_1_fu_1766_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_13_fu_1696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_14_fu_1710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_15_fu_1702_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_16_fu_1716_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_15_fu_1724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_16_fu_1738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_17_fu_1730_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_18_fu_1744_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_17_fu_1752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_18_fu_1776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln236_fu_1770_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_20_fu_1782_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_19_fu_1790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_20_fu_1804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_21_fu_1796_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_12_fu_1663_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal or_ln236_21_fu_1818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_22_fu_1810_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln236_23_fu_1824_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shifted_86_fu_1832_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln671_fu_1840_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln804_fu_1850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln807_fu_1855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_fu_1867_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal out_fu_1867_p7 : STD_LOGIC_VECTOR (22 downto 0);
    signal out_fu_1867_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal out_fu_1867_p9 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_int_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal mul_ln862_fu_1281_p10 : STD_LOGIC_VECTOR (26 downto 0);
    signal clz_fu_341_p0 : STD_LOGIC_VECTOR (25 downto 0);
    signal clz_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_fu_1867_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal out_fu_1867_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal out_fu_1867_p5 : STD_LOGIC_VECTOR (1 downto 0);

    component mpc_fpga_top_opencl_ctlz_26_26_1_0 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (25 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component mpc_fpga_top_opencl_mul_19s_8ns_27_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (18 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component mpc_fpga_top_opencl_sparsemux_7_2_23_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (22 downto 0);
        din2 : IN STD_LOGIC_VECTOR (22 downto 0);
        def : IN STD_LOGIC_VECTOR (22 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component mpc_fpga_top_opencl_fp_recip_fn_recip_lut_fn_ROM_2P_BRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;



begin
    recip_lut_fn_U : component mpc_fpga_top_opencl_fp_recip_fn_recip_lut_fn_ROM_2P_BRAM_1R
    generic map (
        DataWidth => 19,
        AddressRange => 257,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => recip_lut_fn_address0,
        ce0 => recip_lut_fn_ce0_local,
        q0 => recip_lut_fn_q0,
        address1 => recip_lut_fn_address1,
        ce1 => recip_lut_fn_ce1_local,
        q1 => recip_lut_fn_q1);

    ctlz_26_26_1_0_U302 : component mpc_fpga_top_opencl_ctlz_26_26_1_0
    generic map (
        din_WIDTH => 26,
        dout_WIDTH => 26)
    port map (
        din => clz_fu_341_p1,
        dout => clz_fu_341_p3);

    mul_19s_8ns_27_1_0_U303 : component mpc_fpga_top_opencl_mul_19s_8ns_27_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 19,
        din1_WIDTH => 8,
        dout_WIDTH => 27)
    port map (
        din0 => sub_ln862_fu_1270_p2,
        din1 => mul_ln862_fu_1281_p1,
        dout => mul_ln862_fu_1281_p2);

    sparsemux_7_2_23_1_0_U304 : component mpc_fpga_top_opencl_sparsemux_7_2_23_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 23,
        CASE1 => "01",
        din1_WIDTH => 23,
        CASE2 => "00",
        din2_WIDTH => 23,
        def_WIDTH => 23,
        sel_WIDTH => 2,
        dout_WIDTH => 23)
    port map (
        din0 => ap_const_lv23_0,
        din1 => out_fu_1867_p4,
        din2 => sext_ln671_fu_1840_p1,
        def => out_fu_1867_p7,
        sel => out_fu_1867_p8,
        dout => out_fu_1867_p9);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                abs_raw_signed_2_reg_1898 <= abs_raw_signed_2_fu_333_p3;
                abs_raw_signed_2_reg_1898_pp0_iter1_reg <= abs_raw_signed_2_reg_1898;
                add_ln822_reg_1951 <= add_ln822_fu_387_p2;
                icmp_ln221_1_reg_1993 <= icmp_ln221_1_fu_676_p2;
                icmp_ln221_1_reg_1993_pp0_iter2_reg <= icmp_ln221_1_reg_1993;
                icmp_ln221_1_reg_1993_pp0_iter3_reg <= icmp_ln221_1_reg_1993_pp0_iter2_reg;
                icmp_ln221_1_reg_1993_pp0_iter4_reg <= icmp_ln221_1_reg_1993_pp0_iter3_reg;
                icmp_ln221_1_reg_1993_pp0_iter5_reg <= icmp_ln221_1_reg_1993_pp0_iter4_reg;
                icmp_ln221_2_reg_2006 <= icmp_ln221_2_fu_759_p2;
                icmp_ln221_2_reg_2006_pp0_iter3_reg <= icmp_ln221_2_reg_2006;
                icmp_ln221_2_reg_2006_pp0_iter4_reg <= icmp_ln221_2_reg_2006_pp0_iter3_reg;
                icmp_ln221_2_reg_2006_pp0_iter5_reg <= icmp_ln221_2_reg_2006_pp0_iter4_reg;
                icmp_ln221_3_reg_2017 <= icmp_ln221_3_fu_805_p2;
                icmp_ln221_3_reg_2017_pp0_iter3_reg <= icmp_ln221_3_reg_2017;
                icmp_ln221_3_reg_2017_pp0_iter4_reg <= icmp_ln221_3_reg_2017_pp0_iter3_reg;
                icmp_ln221_3_reg_2017_pp0_iter5_reg <= icmp_ln221_3_reg_2017_pp0_iter4_reg;
                icmp_ln221_4_reg_2028 <= icmp_ln221_4_fu_851_p2;
                icmp_ln221_4_reg_2028_pp0_iter3_reg <= icmp_ln221_4_reg_2028;
                icmp_ln221_4_reg_2028_pp0_iter4_reg <= icmp_ln221_4_reg_2028_pp0_iter3_reg;
                icmp_ln221_4_reg_2028_pp0_iter5_reg <= icmp_ln221_4_reg_2028_pp0_iter4_reg;
                icmp_ln221_5_reg_2039 <= icmp_ln221_5_fu_897_p2;
                icmp_ln221_5_reg_2039_pp0_iter3_reg <= icmp_ln221_5_reg_2039;
                icmp_ln221_5_reg_2039_pp0_iter4_reg <= icmp_ln221_5_reg_2039_pp0_iter3_reg;
                icmp_ln221_5_reg_2039_pp0_iter5_reg <= icmp_ln221_5_reg_2039_pp0_iter4_reg;
                icmp_ln221_6_reg_2050 <= icmp_ln221_6_fu_943_p2;
                icmp_ln221_6_reg_2050_pp0_iter3_reg <= icmp_ln221_6_reg_2050;
                icmp_ln221_6_reg_2050_pp0_iter4_reg <= icmp_ln221_6_reg_2050_pp0_iter3_reg;
                icmp_ln221_6_reg_2050_pp0_iter5_reg <= icmp_ln221_6_reg_2050_pp0_iter4_reg;
                icmp_ln221_7_reg_2061 <= icmp_ln221_7_fu_989_p2;
                icmp_ln221_7_reg_2061_pp0_iter3_reg <= icmp_ln221_7_reg_2061;
                icmp_ln221_7_reg_2061_pp0_iter4_reg <= icmp_ln221_7_reg_2061_pp0_iter3_reg;
                icmp_ln221_7_reg_2061_pp0_iter5_reg <= icmp_ln221_7_reg_2061_pp0_iter4_reg;
                icmp_ln221_8_reg_2072 <= icmp_ln221_8_fu_1035_p2;
                icmp_ln221_8_reg_2072_pp0_iter3_reg <= icmp_ln221_8_reg_2072;
                icmp_ln221_8_reg_2072_pp0_iter4_reg <= icmp_ln221_8_reg_2072_pp0_iter3_reg;
                icmp_ln221_8_reg_2072_pp0_iter5_reg <= icmp_ln221_8_reg_2072_pp0_iter4_reg;
                icmp_ln221_reg_1981 <= icmp_ln221_fu_664_p2;
                icmp_ln221_reg_1981_pp0_iter2_reg <= icmp_ln221_reg_1981;
                icmp_ln221_reg_1981_pp0_iter3_reg <= icmp_ln221_reg_1981_pp0_iter2_reg;
                icmp_ln221_reg_1981_pp0_iter4_reg <= icmp_ln221_reg_1981_pp0_iter3_reg;
                icmp_ln221_reg_1981_pp0_iter5_reg <= icmp_ln221_reg_1981_pp0_iter4_reg;
                icmp_ln223_10_reg_2089 <= icmp_ln223_10_fu_1105_p2;
                icmp_ln223_10_reg_2089_pp0_iter3_reg <= icmp_ln223_10_reg_2089;
                icmp_ln223_10_reg_2089_pp0_iter4_reg <= icmp_ln223_10_reg_2089_pp0_iter3_reg;
                icmp_ln223_10_reg_2089_pp0_iter5_reg <= icmp_ln223_10_reg_2089_pp0_iter4_reg;
                icmp_ln223_11_reg_2094 <= icmp_ln223_11_fu_1129_p2;
                icmp_ln223_11_reg_2094_pp0_iter3_reg <= icmp_ln223_11_reg_2094;
                icmp_ln223_11_reg_2094_pp0_iter4_reg <= icmp_ln223_11_reg_2094_pp0_iter3_reg;
                icmp_ln223_11_reg_2094_pp0_iter5_reg <= icmp_ln223_11_reg_2094_pp0_iter4_reg;
                icmp_ln223_12_reg_2100 <= icmp_ln223_12_fu_1153_p2;
                icmp_ln223_12_reg_2100_pp0_iter3_reg <= icmp_ln223_12_reg_2100;
                icmp_ln223_12_reg_2100_pp0_iter4_reg <= icmp_ln223_12_reg_2100_pp0_iter3_reg;
                icmp_ln223_12_reg_2100_pp0_iter5_reg <= icmp_ln223_12_reg_2100_pp0_iter4_reg;
                icmp_ln223_13_reg_2105 <= icmp_ln223_13_fu_1177_p2;
                icmp_ln223_13_reg_2105_pp0_iter3_reg <= icmp_ln223_13_reg_2105;
                icmp_ln223_13_reg_2105_pp0_iter4_reg <= icmp_ln223_13_reg_2105_pp0_iter3_reg;
                icmp_ln223_13_reg_2105_pp0_iter5_reg <= icmp_ln223_13_reg_2105_pp0_iter4_reg;
                icmp_ln223_14_reg_2111 <= icmp_ln223_14_fu_1201_p2;
                icmp_ln223_14_reg_2111_pp0_iter3_reg <= icmp_ln223_14_reg_2111;
                icmp_ln223_14_reg_2111_pp0_iter4_reg <= icmp_ln223_14_reg_2111_pp0_iter3_reg;
                icmp_ln223_14_reg_2111_pp0_iter5_reg <= icmp_ln223_14_reg_2111_pp0_iter4_reg;
                icmp_ln223_15_reg_2116 <= icmp_ln223_15_fu_1225_p2;
                icmp_ln223_15_reg_2116_pp0_iter3_reg <= icmp_ln223_15_reg_2116;
                icmp_ln223_15_reg_2116_pp0_iter4_reg <= icmp_ln223_15_reg_2116_pp0_iter3_reg;
                icmp_ln223_15_reg_2116_pp0_iter5_reg <= icmp_ln223_15_reg_2116_pp0_iter4_reg;
                icmp_ln223_1_reg_2000 <= icmp_ln223_1_fu_682_p2;
                icmp_ln223_1_reg_2000_pp0_iter2_reg <= icmp_ln223_1_reg_2000;
                icmp_ln223_1_reg_2000_pp0_iter3_reg <= icmp_ln223_1_reg_2000_pp0_iter2_reg;
                icmp_ln223_1_reg_2000_pp0_iter4_reg <= icmp_ln223_1_reg_2000_pp0_iter3_reg;
                icmp_ln223_1_reg_2000_pp0_iter5_reg <= icmp_ln223_1_reg_2000_pp0_iter4_reg;
                icmp_ln223_2_reg_2012 <= icmp_ln223_2_fu_781_p2;
                icmp_ln223_2_reg_2012_pp0_iter3_reg <= icmp_ln223_2_reg_2012;
                icmp_ln223_2_reg_2012_pp0_iter4_reg <= icmp_ln223_2_reg_2012_pp0_iter3_reg;
                icmp_ln223_2_reg_2012_pp0_iter5_reg <= icmp_ln223_2_reg_2012_pp0_iter4_reg;
                icmp_ln223_3_reg_2023 <= icmp_ln223_3_fu_827_p2;
                icmp_ln223_3_reg_2023_pp0_iter3_reg <= icmp_ln223_3_reg_2023;
                icmp_ln223_3_reg_2023_pp0_iter4_reg <= icmp_ln223_3_reg_2023_pp0_iter3_reg;
                icmp_ln223_3_reg_2023_pp0_iter5_reg <= icmp_ln223_3_reg_2023_pp0_iter4_reg;
                icmp_ln223_4_reg_2034 <= icmp_ln223_4_fu_873_p2;
                icmp_ln223_4_reg_2034_pp0_iter3_reg <= icmp_ln223_4_reg_2034;
                icmp_ln223_4_reg_2034_pp0_iter4_reg <= icmp_ln223_4_reg_2034_pp0_iter3_reg;
                icmp_ln223_4_reg_2034_pp0_iter5_reg <= icmp_ln223_4_reg_2034_pp0_iter4_reg;
                icmp_ln223_5_reg_2045 <= icmp_ln223_5_fu_919_p2;
                icmp_ln223_5_reg_2045_pp0_iter3_reg <= icmp_ln223_5_reg_2045;
                icmp_ln223_5_reg_2045_pp0_iter4_reg <= icmp_ln223_5_reg_2045_pp0_iter3_reg;
                icmp_ln223_5_reg_2045_pp0_iter5_reg <= icmp_ln223_5_reg_2045_pp0_iter4_reg;
                icmp_ln223_6_reg_2056 <= icmp_ln223_6_fu_965_p2;
                icmp_ln223_6_reg_2056_pp0_iter3_reg <= icmp_ln223_6_reg_2056;
                icmp_ln223_6_reg_2056_pp0_iter4_reg <= icmp_ln223_6_reg_2056_pp0_iter3_reg;
                icmp_ln223_6_reg_2056_pp0_iter5_reg <= icmp_ln223_6_reg_2056_pp0_iter4_reg;
                icmp_ln223_7_reg_2067 <= icmp_ln223_7_fu_1011_p2;
                icmp_ln223_7_reg_2067_pp0_iter3_reg <= icmp_ln223_7_reg_2067;
                icmp_ln223_7_reg_2067_pp0_iter4_reg <= icmp_ln223_7_reg_2067_pp0_iter3_reg;
                icmp_ln223_7_reg_2067_pp0_iter5_reg <= icmp_ln223_7_reg_2067_pp0_iter4_reg;
                icmp_ln223_8_reg_2078 <= icmp_ln223_8_fu_1057_p2;
                icmp_ln223_8_reg_2078_pp0_iter3_reg <= icmp_ln223_8_reg_2078;
                icmp_ln223_8_reg_2078_pp0_iter4_reg <= icmp_ln223_8_reg_2078_pp0_iter3_reg;
                icmp_ln223_8_reg_2078_pp0_iter5_reg <= icmp_ln223_8_reg_2078_pp0_iter4_reg;
                icmp_ln223_9_reg_2083 <= icmp_ln223_9_fu_1081_p2;
                icmp_ln223_9_reg_2083_pp0_iter3_reg <= icmp_ln223_9_reg_2083;
                icmp_ln223_9_reg_2083_pp0_iter4_reg <= icmp_ln223_9_reg_2083_pp0_iter3_reg;
                icmp_ln223_9_reg_2083_pp0_iter5_reg <= icmp_ln223_9_reg_2083_pp0_iter4_reg;
                icmp_ln223_reg_1987 <= icmp_ln223_fu_670_p2;
                icmp_ln223_reg_1987_pp0_iter2_reg <= icmp_ln223_reg_1987;
                icmp_ln223_reg_1987_pp0_iter3_reg <= icmp_ln223_reg_1987_pp0_iter2_reg;
                icmp_ln223_reg_1987_pp0_iter4_reg <= icmp_ln223_reg_1987_pp0_iter3_reg;
                icmp_ln223_reg_1987_pp0_iter5_reg <= icmp_ln223_reg_1987_pp0_iter4_reg;
                icmp_ln804_reg_1887 <= icmp_ln804_fu_313_p2;
                icmp_ln804_reg_1887_pp0_iter1_reg <= icmp_ln804_reg_1887;
                icmp_ln804_reg_1887_pp0_iter2_reg <= icmp_ln804_reg_1887_pp0_iter1_reg;
                icmp_ln804_reg_1887_pp0_iter3_reg <= icmp_ln804_reg_1887_pp0_iter2_reg;
                icmp_ln804_reg_1887_pp0_iter4_reg <= icmp_ln804_reg_1887_pp0_iter3_reg;
                icmp_ln804_reg_1887_pp0_iter5_reg <= icmp_ln804_reg_1887_pp0_iter4_reg;
                icmp_ln819_reg_1936 <= icmp_ln819_fu_359_p2;
                icmp_ln821_reg_1946 <= icmp_ln821_fu_381_p2;
                lut_idx_reg_2122 <= x_norm_raw_72_fu_1230_p3(15 downto 8);
                neg_reg_1893 <= x_int_reg(25 downto 25);
                neg_reg_1893_pp0_iter1_reg <= neg_reg_1893;
                neg_reg_1893_pp0_iter2_reg <= neg_reg_1893_pp0_iter1_reg;
                neg_reg_1893_pp0_iter3_reg <= neg_reg_1893_pp0_iter2_reg;
                neg_reg_1893_pp0_iter4_reg <= neg_reg_1893_pp0_iter3_reg;
                neg_reg_1893_pp0_iter5_reg <= neg_reg_1893_pp0_iter4_reg;
                shift_4_reg_1956 <= shift_4_fu_656_p3;
                shift_reg_1941 <= shift_fu_365_p2;
                trunc_ln858_reg_2128 <= trunc_ln858_fu_1248_p1;
                trunc_ln858_reg_2128_pp0_iter3_reg <= trunc_ln858_reg_2128;
                trunc_ln858_reg_2128_pp0_iter4_reg <= trunc_ln858_reg_2128_pp0_iter3_reg;
                trunc_ln_reg_2155 <= mul_ln862_fu_1281_p2(26 downto 8);
                v0_reg_2143 <= recip_lut_fn_q1;
                v0_reg_2143_pp0_iter5_reg <= v0_reg_2143;
                v1_reg_2150 <= recip_lut_fn_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= out_fu_1867_p9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_int_reg <= x;
            end if;
        end if;
    end process;
    abs_raw_signed_2_fu_333_p3 <= 
        abs_raw_signed_fu_327_p2 when (neg_fu_319_p3(0) = '1') else 
        x_int_reg;
    abs_raw_signed_fu_327_p2 <= std_logic_vector(unsigned(ap_const_lv26_0) - unsigned(x_int_reg));
    add_ln822_fu_387_p2 <= std_logic_vector(unsigned(msb_fu_353_p2) + unsigned(ap_const_lv6_30));
    add_ln860_fu_1259_p2 <= std_logic_vector(unsigned(zext_ln848_fu_1252_p1) + unsigned(ap_const_lv9_1));
    add_ln862_fu_1303_p2 <= std_logic_vector(signed(trunc_ln_reg_2155) + signed(v0_reg_2143_pp0_iter5_reg));
    and_ln807_fu_1855_p2 <= (xor_ln804_fu_1850_p2 and neg_reg_1893_pp0_iter5_reg);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(out_fu_1867_p9, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= out_fu_1867_p9;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    clz_fu_341_p1 <= 
        abs_raw_signed_fu_327_p2 when (neg_fu_319_p3(0) = '1') else 
        x_int_reg;
    est_raw_fu_1307_p2 <= std_logic_vector(signed(sext_ln862_1_fu_1300_p1) + signed(zext_ln859_1_fu_1297_p1));
    icmp_ln221_1_fu_676_p2 <= "1" when (shift_4_fu_656_p3 = ap_const_lv6_2) else "0";
    icmp_ln221_2_fu_759_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_3) else "0";
    icmp_ln221_3_fu_805_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_4) else "0";
    icmp_ln221_4_fu_851_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_5) else "0";
    icmp_ln221_5_fu_897_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_6) else "0";
    icmp_ln221_6_fu_943_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_7) else "0";
    icmp_ln221_7_fu_989_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_8) else "0";
    icmp_ln221_8_fu_1035_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_9) else "0";
    icmp_ln221_fu_664_p2 <= "1" when (shift_4_fu_656_p3 = ap_const_lv6_1) else "0";
    icmp_ln223_10_fu_1105_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_35) else "0";
    icmp_ln223_11_fu_1129_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_34) else "0";
    icmp_ln223_12_fu_1153_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_33) else "0";
    icmp_ln223_13_fu_1177_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_32) else "0";
    icmp_ln223_14_fu_1201_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_31) else "0";
    icmp_ln223_15_fu_1225_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_30) else "0";
    icmp_ln223_1_fu_682_p2 <= "1" when (shift_4_fu_656_p3 = ap_const_lv6_3E) else "0";
    icmp_ln223_2_fu_781_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_3D) else "0";
    icmp_ln223_3_fu_827_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_3C) else "0";
    icmp_ln223_4_fu_873_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_3B) else "0";
    icmp_ln223_5_fu_919_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_3A) else "0";
    icmp_ln223_6_fu_965_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_39) else "0";
    icmp_ln223_7_fu_1011_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_38) else "0";
    icmp_ln223_8_fu_1057_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_37) else "0";
    icmp_ln223_9_fu_1081_p2 <= "1" when (shift_4_reg_1956 = ap_const_lv6_36) else "0";
    icmp_ln223_fu_670_p2 <= "1" when (shift_4_fu_656_p3 = ap_const_lv6_3F) else "0";
    icmp_ln804_fu_313_p2 <= "1" when (x_int_reg = ap_const_lv26_0) else "0";
    icmp_ln819_fu_359_p2 <= "1" when (signed(msb_fu_353_p2) > signed(ap_const_lv6_11)) else "0";
    icmp_ln821_fu_381_p2 <= "0" when (tmp_fu_371_p4 = ap_const_lv2_1) else "1";
    icmp_ln829_1_fu_419_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_2) else "0";
    icmp_ln829_2_fu_425_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_3) else "0";
    icmp_ln829_3_fu_431_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_4) else "0";
    icmp_ln829_4_fu_437_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_5) else "0";
    icmp_ln829_5_fu_443_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_6) else "0";
    icmp_ln829_6_fu_449_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_7) else "0";
    icmp_ln829_7_fu_455_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_8) else "0";
    icmp_ln829_fu_413_p2 <= "1" when (shift_1_fu_399_p3 = ap_const_lv6_1) else "0";
    icmp_ln834_fu_636_p2 <= "0" when (select_ln829_7_fu_628_p3 = ap_const_lv9_0) else "1";
    msb_fu_353_p2 <= std_logic_vector(unsigned(ap_const_lv6_19) - unsigned(trunc_ln816_fu_349_p1));
    mul_ln862_fu_1281_p1 <= mul_ln862_fu_1281_p10(8 - 1 downto 0);
    mul_ln862_fu_1281_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln858_reg_2128_pp0_iter4_reg),27));
    neg_fu_319_p3 <= x_int_reg(25 downto 25);
    or_ln236_10_fu_1648_p2 <= (icmp_ln223_1_reg_2000_pp0_iter5_reg or icmp_ln221_2_reg_2006_pp0_iter5_reg);
    or_ln236_11_fu_1659_p2 <= (icmp_ln223_reg_1987_pp0_iter5_reg or icmp_ln221_1_reg_1993_pp0_iter5_reg);
    or_ln236_12_fu_1678_p2 <= (or_ln236_fu_1538_p2 or or_ln236_1_fu_1549_p2);
    or_ln236_13_fu_1696_p2 <= (or_ln236_3_fu_1571_p2 or or_ln236_2_fu_1560_p2);
    or_ln236_14_fu_1710_p2 <= (or_ln236_5_fu_1593_p2 or or_ln236_4_fu_1582_p2);
    or_ln236_15_fu_1724_p2 <= (or_ln236_7_fu_1615_p2 or or_ln236_6_fu_1604_p2);
    or_ln236_16_fu_1738_p2 <= (or_ln236_9_fu_1637_p2 or or_ln236_8_fu_1626_p2);
    or_ln236_17_fu_1752_p2 <= (or_ln236_11_fu_1659_p2 or or_ln236_10_fu_1648_p2);
    or_ln236_18_fu_1776_p2 <= (or_ln236_13_fu_1696_p2 or or_ln236_12_fu_1678_p2);
    or_ln236_19_fu_1790_p2 <= (or_ln236_15_fu_1724_p2 or or_ln236_14_fu_1710_p2);
    or_ln236_1_fu_1549_p2 <= (icmp_ln223_13_reg_2105_pp0_iter5_reg or icmp_ln223_12_reg_2100_pp0_iter5_reg);
    or_ln236_20_fu_1804_p2 <= (or_ln236_17_fu_1752_p2 or or_ln236_16_fu_1738_p2);
    or_ln236_21_fu_1818_p2 <= (or_ln236_19_fu_1790_p2 or or_ln236_18_fu_1776_p2);
    or_ln236_2_fu_1560_p2 <= (icmp_ln223_11_reg_2094_pp0_iter5_reg or icmp_ln223_10_reg_2089_pp0_iter5_reg);
    or_ln236_3_fu_1571_p2 <= (icmp_ln223_9_reg_2083_pp0_iter5_reg or icmp_ln223_8_reg_2078_pp0_iter5_reg);
    or_ln236_4_fu_1582_p2 <= (icmp_ln223_7_reg_2067_pp0_iter5_reg or icmp_ln221_8_reg_2072_pp0_iter5_reg);
    or_ln236_5_fu_1593_p2 <= (icmp_ln223_6_reg_2056_pp0_iter5_reg or icmp_ln221_7_reg_2061_pp0_iter5_reg);
    or_ln236_6_fu_1604_p2 <= (icmp_ln223_5_reg_2045_pp0_iter5_reg or icmp_ln221_6_reg_2050_pp0_iter5_reg);
    or_ln236_7_fu_1615_p2 <= (icmp_ln223_4_reg_2034_pp0_iter5_reg or icmp_ln221_5_reg_2039_pp0_iter5_reg);
    or_ln236_8_fu_1626_p2 <= (icmp_ln223_3_reg_2023_pp0_iter5_reg or icmp_ln221_4_reg_2028_pp0_iter5_reg);
    or_ln236_9_fu_1637_p2 <= (icmp_ln223_2_reg_2012_pp0_iter5_reg or icmp_ln221_3_reg_2017_pp0_iter5_reg);
    or_ln236_fu_1538_p2 <= (icmp_ln223_15_reg_2116_pp0_iter5_reg or icmp_ln223_14_reg_2111_pp0_iter5_reg);
    out_fu_1867_p4 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(sext_ln671_fu_1840_p1));
    out_fu_1867_p7 <= "XXXXXXXXXXXXXXXXXXXXXXX";
    out_fu_1867_p8 <= (icmp_ln804_reg_1887_pp0_iter5_reg & and_ln807_fu_1855_p2);
    recip_lut_fn_address0 <= zext_ln860_fu_1265_p1(9 - 1 downto 0);
    recip_lut_fn_address1 <= zext_ln859_fu_1255_p1(9 - 1 downto 0);

    recip_lut_fn_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            recip_lut_fn_ce0_local <= ap_const_logic_1;
        else 
            recip_lut_fn_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    recip_lut_fn_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            recip_lut_fn_ce1_local <= ap_const_logic_1;
        else 
            recip_lut_fn_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln236_10_fu_1641_p3 <= 
        shifted_54_fu_1375_p1 when (icmp_ln221_2_reg_2006_pp0_iter5_reg(0) = '1') else 
        shifted_53_fu_1357_p3;
    select_ln236_11_fu_1652_p3 <= 
        shifted_52_fu_1353_p1 when (icmp_ln221_1_reg_1993_pp0_iter5_reg(0) = '1') else 
        sext_ln231_1_fu_1339_p1;
    select_ln236_12_fu_1663_p3 <= 
        shifted_50_fu_1327_p1 when (icmp_ln221_reg_1981_pp0_iter5_reg(0) = '1') else 
        sext_ln231_fu_1313_p1;
    select_ln236_13_fu_1670_p3 <= 
        select_ln236_fu_1531_p3 when (or_ln236_fu_1538_p2(0) = '1') else 
        select_ln236_1_fu_1542_p3;
    select_ln236_14_fu_1684_p3 <= 
        select_ln236_2_fu_1553_p3 when (or_ln236_2_fu_1560_p2(0) = '1') else 
        select_ln236_3_fu_1564_p3;
    select_ln236_15_fu_1702_p3 <= 
        select_ln236_4_fu_1575_p3 when (or_ln236_4_fu_1582_p2(0) = '1') else 
        select_ln236_5_fu_1586_p3;
    select_ln236_16_fu_1716_p3 <= 
        select_ln236_6_fu_1597_p3 when (or_ln236_6_fu_1604_p2(0) = '1') else 
        select_ln236_7_fu_1608_p3;
    select_ln236_17_fu_1730_p3 <= 
        select_ln236_8_fu_1619_p3 when (or_ln236_8_fu_1626_p2(0) = '1') else 
        select_ln236_9_fu_1630_p3;
    select_ln236_18_fu_1744_p3 <= 
        select_ln236_10_fu_1641_p3 when (or_ln236_10_fu_1648_p2(0) = '1') else 
        select_ln236_11_fu_1652_p3;
    select_ln236_19_fu_1758_p3 <= 
        select_ln236_13_fu_1670_p3 when (or_ln236_12_fu_1678_p2(0) = '1') else 
        zext_ln236_fu_1692_p1;
    select_ln236_1_fu_1542_p3 <= 
        ap_const_lv5_E when (icmp_ln223_13_reg_2105_pp0_iter5_reg(0) = '1') else 
        ap_const_lv5_D;
    select_ln236_20_fu_1782_p3 <= 
        select_ln236_15_fu_1702_p3 when (or_ln236_14_fu_1710_p2(0) = '1') else 
        select_ln236_16_fu_1716_p3;
    select_ln236_21_fu_1796_p3 <= 
        select_ln236_17_fu_1730_p3 when (or_ln236_16_fu_1738_p2(0) = '1') else 
        select_ln236_18_fu_1744_p3;
    select_ln236_22_fu_1810_p3 <= 
        shl_ln236_fu_1770_p2 when (or_ln236_18_fu_1776_p2(0) = '1') else 
        select_ln236_20_fu_1782_p3;
    select_ln236_23_fu_1824_p3 <= 
        select_ln236_21_fu_1796_p3 when (or_ln236_20_fu_1804_p2(0) = '1') else 
        select_ln236_12_fu_1663_p3;
    select_ln236_2_fu_1553_p3 <= 
        ap_const_lv4_C when (icmp_ln223_11_reg_2094_pp0_iter5_reg(0) = '1') else 
        ap_const_lv4_B;
    select_ln236_3_fu_1564_p3 <= 
        ap_const_lv4_A when (icmp_ln223_9_reg_2083_pp0_iter5_reg(0) = '1') else 
        ap_const_lv4_9;
    select_ln236_4_fu_1575_p3 <= 
        sext_ln235_4_fu_1527_p1 when (icmp_ln221_8_reg_2072_pp0_iter5_reg(0) = '1') else 
        shifted_61_fu_1509_p3;
    select_ln236_5_fu_1586_p3 <= 
        sext_ln235_3_fu_1501_p1 when (icmp_ln221_7_reg_2061_pp0_iter5_reg(0) = '1') else 
        shifted_60_fu_1483_p3;
    select_ln236_6_fu_1597_p3 <= 
        sext_ln235_2_fu_1475_p1 when (icmp_ln221_6_reg_2050_pp0_iter5_reg(0) = '1') else 
        shifted_59_fu_1457_p3;
    select_ln236_7_fu_1608_p3 <= 
        sext_ln235_1_fu_1449_p1 when (icmp_ln221_5_reg_2039_pp0_iter5_reg(0) = '1') else 
        shifted_58_fu_1431_p3;
    select_ln236_8_fu_1619_p3 <= 
        sext_ln235_fu_1423_p1 when (icmp_ln221_4_reg_2028_pp0_iter5_reg(0) = '1') else 
        shifted_57_fu_1405_p3;
    select_ln236_9_fu_1630_p3 <= 
        shifted_56_fu_1397_p1 when (icmp_ln221_3_reg_2017_pp0_iter5_reg(0) = '1') else 
        shifted_55_fu_1379_p3;
    select_ln236_fu_1531_p3 <= 
        ap_const_lv5_10 when (icmp_ln223_15_reg_2116_pp0_iter5_reg(0) = '1') else 
        ap_const_lv5_F;
    select_ln829_1_fu_580_p3 <= 
        zext_ln834_6_fu_546_p1 when (icmp_ln829_1_fu_419_p2(0) = '1') else 
        select_ln829_fu_572_p3;
    select_ln829_2_fu_588_p3 <= 
        zext_ln834_5_fu_533_p1 when (icmp_ln829_2_fu_425_p2(0) = '1') else 
        select_ln829_1_fu_580_p3;
    select_ln829_3_fu_596_p3 <= 
        zext_ln834_4_fu_520_p1 when (icmp_ln829_3_fu_431_p2(0) = '1') else 
        select_ln829_2_fu_588_p3;
    select_ln829_4_fu_604_p3 <= 
        zext_ln834_3_fu_507_p1 when (icmp_ln829_4_fu_437_p2(0) = '1') else 
        select_ln829_3_fu_596_p3;
    select_ln829_5_fu_612_p3 <= 
        zext_ln834_2_fu_494_p1 when (icmp_ln829_5_fu_443_p2(0) = '1') else 
        select_ln829_4_fu_604_p3;
    select_ln829_6_fu_620_p3 <= 
        zext_ln834_1_fu_481_p1 when (icmp_ln829_6_fu_449_p2(0) = '1') else 
        select_ln829_5_fu_612_p3;
    select_ln829_7_fu_628_p3 <= 
        zext_ln834_fu_468_p1 when (icmp_ln829_7_fu_455_p2(0) = '1') else 
        select_ln829_6_fu_620_p3;
    select_ln829_fu_572_p3 <= 
        zext_ln834_7_fu_559_p1 when (icmp_ln829_fu_413_p2(0) = '1') else 
        tmp_65_fu_563_p4;
        sext_ln231_1_fu_1339_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shifted_51_fu_1331_p3),22));

        sext_ln231_fu_1313_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(est_raw_fu_1307_p2),22));

        sext_ln235_1_fu_1449_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_71_fu_1439_p4),22));

        sext_ln235_2_fu_1475_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_72_fu_1465_p4),22));

        sext_ln235_3_fu_1501_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_73_fu_1491_p4),22));

        sext_ln235_4_fu_1527_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_74_fu_1517_p4),22));

        sext_ln235_fu_1423_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_70_fu_1413_p4),22));

        sext_ln671_fu_1840_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shifted_86_fu_1832_p3),23));

        sext_ln862_1_fu_1300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_2155),20));

    shift_1_fu_399_p3 <= 
        shift_reg_1941 when (icmp_ln819_reg_1936(0) = '1') else 
        spec_select_fu_393_p3;
    shift_2_fu_642_p2 <= std_logic_vector(unsigned(shift_1_fu_399_p3) + unsigned(ap_const_lv6_1));
    shift_3_fu_648_p3 <= 
        shift_2_fu_642_p2 when (icmp_ln834_fu_636_p2(0) = '1') else 
        shift_1_fu_399_p3;
    shift_4_fu_656_p3 <= 
        shift_1_fu_399_p3 when (tmp_56_fu_405_p3(0) = '1') else 
        shift_3_fu_648_p3;
    shift_fu_365_p2 <= std_logic_vector(unsigned(msb_fu_353_p2) + unsigned(ap_const_lv6_2F));
        shifted_50_fu_1327_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_66_fu_1317_p4),22));

    shifted_51_fu_1331_p3 <= (est_raw_fu_1307_p2 & ap_const_lv1_0);
        shifted_52_fu_1353_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_67_fu_1343_p4),22));

    shifted_53_fu_1357_p3 <= (est_raw_fu_1307_p2 & ap_const_lv2_0);
        shifted_54_fu_1375_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_68_fu_1365_p4),22));

    shifted_55_fu_1379_p3 <= (add_ln862_fu_1303_p2 & ap_const_lv3_0);
        shifted_56_fu_1397_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_69_fu_1387_p4),22));

    shifted_57_fu_1405_p3 <= (trunc_ln237_fu_1401_p1 & ap_const_lv4_0);
    shifted_58_fu_1431_p3 <= (trunc_ln237_1_fu_1427_p1 & ap_const_lv5_0);
    shifted_59_fu_1457_p3 <= (trunc_ln237_2_fu_1453_p1 & ap_const_lv6_0);
    shifted_60_fu_1483_p3 <= (trunc_ln237_3_fu_1479_p1 & ap_const_lv7_0);
    shifted_61_fu_1509_p3 <= (trunc_ln237_4_fu_1505_p1 & ap_const_lv8_0);
    shifted_63_fu_691_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(16 downto 1);
    shifted_64_fu_710_p3 <= (trunc_ln224_fu_707_p1 & ap_const_lv1_0);
    shifted_65_fu_725_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(17 downto 2);
    shifted_66_fu_744_p3 <= (trunc_ln224_1_fu_741_p1 & ap_const_lv2_0);
    shifted_67_fu_764_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(18 downto 3);
    shifted_68_fu_789_p3 <= (trunc_ln224_2_fu_786_p1 & ap_const_lv3_0);
    shifted_69_fu_810_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(19 downto 4);
    shifted_70_fu_835_p3 <= (trunc_ln224_3_fu_832_p1 & ap_const_lv4_0);
    shifted_71_fu_881_p3 <= (trunc_ln224_4_fu_878_p1 & ap_const_lv5_0);
    shifted_72_fu_902_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(21 downto 6);
    shifted_73_fu_927_p3 <= (trunc_ln224_5_fu_924_p1 & ap_const_lv6_0);
    shifted_74_fu_948_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(22 downto 7);
    shifted_75_fu_973_p3 <= (trunc_ln224_6_fu_970_p1 & ap_const_lv7_0);
    shifted_76_fu_994_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(23 downto 8);
    shifted_77_fu_1019_p3 <= (trunc_ln224_7_fu_1016_p1 & ap_const_lv8_0);
    shifted_78_fu_1040_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(24 downto 9);
    shifted_79_fu_1065_p3 <= (trunc_ln224_8_fu_1062_p1 & ap_const_lv9_0);
    shifted_80_fu_1089_p3 <= (trunc_ln224_9_fu_1086_p1 & ap_const_lv10_0);
    shifted_81_fu_1113_p3 <= (trunc_ln224_10_fu_1110_p1 & ap_const_lv11_0);
    shifted_82_fu_1137_p3 <= (trunc_ln224_11_fu_1134_p1 & ap_const_lv12_0);
    shifted_83_fu_1161_p3 <= (trunc_ln224_12_fu_1158_p1 & ap_const_lv13_0);
    shifted_84_fu_1185_p3 <= (trunc_ln224_13_fu_1182_p1 & ap_const_lv14_0);
    shifted_85_fu_1209_p3 <= (trunc_ln224_14_fu_1206_p1 & ap_const_lv15_0);
    shifted_86_fu_1832_p3 <= 
        select_ln236_22_fu_1810_p3 when (or_ln236_21_fu_1818_p2(0) = '1') else 
        select_ln236_23_fu_1824_p3;
    shifted_fu_856_p4 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(20 downto 5);
    shl_ln236_fu_1770_p2 <= std_logic_vector(shift_left(unsigned(sext_ln231_fu_1313_p1),to_integer(unsigned('0' & zext_ln236_1_fu_1766_p1(22-1 downto 0)))));
    spec_select_fu_393_p3 <= 
        add_ln822_reg_1951 when (icmp_ln821_reg_1946(0) = '1') else 
        ap_const_lv6_0;
    sub_ln862_fu_1270_p2 <= std_logic_vector(unsigned(v1_reg_2150) - unsigned(v0_reg_2143));
    tmp_56_fu_405_p3 <= shift_1_fu_399_p3(5 downto 5);
    tmp_57_fu_461_p3 <= abs_raw_signed_2_reg_1898(25 downto 25);
    tmp_58_fu_472_p4 <= abs_raw_signed_2_reg_1898(25 downto 24);
    tmp_59_fu_485_p4 <= abs_raw_signed_2_reg_1898(25 downto 23);
    tmp_60_fu_498_p4 <= abs_raw_signed_2_reg_1898(25 downto 22);
    tmp_61_fu_511_p4 <= abs_raw_signed_2_reg_1898(25 downto 21);
    tmp_62_fu_524_p4 <= abs_raw_signed_2_reg_1898(25 downto 20);
    tmp_63_fu_537_p4 <= abs_raw_signed_2_reg_1898(25 downto 19);
    tmp_64_fu_550_p4 <= abs_raw_signed_2_reg_1898(25 downto 18);
    tmp_65_fu_563_p4 <= abs_raw_signed_2_reg_1898(25 downto 17);
    tmp_66_fu_1317_p4 <= est_raw_fu_1307_p2(19 downto 1);
    tmp_67_fu_1343_p4 <= est_raw_fu_1307_p2(19 downto 2);
    tmp_68_fu_1365_p4 <= est_raw_fu_1307_p2(19 downto 3);
    tmp_69_fu_1387_p4 <= est_raw_fu_1307_p2(19 downto 4);
    tmp_70_fu_1413_p4 <= est_raw_fu_1307_p2(19 downto 5);
    tmp_71_fu_1439_p4 <= est_raw_fu_1307_p2(19 downto 6);
    tmp_72_fu_1465_p4 <= est_raw_fu_1307_p2(19 downto 7);
    tmp_73_fu_1491_p4 <= est_raw_fu_1307_p2(19 downto 8);
    tmp_74_fu_1517_p4 <= est_raw_fu_1307_p2(19 downto 9);
    tmp_fu_371_p4 <= msb_fu_353_p2(5 downto 4);
    trunc_ln224_10_fu_1110_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(5 - 1 downto 0);
    trunc_ln224_11_fu_1134_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(4 - 1 downto 0);
    trunc_ln224_12_fu_1158_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(3 - 1 downto 0);
    trunc_ln224_13_fu_1182_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(2 - 1 downto 0);
    trunc_ln224_14_fu_1206_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(1 - 1 downto 0);
    trunc_ln224_1_fu_741_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(14 - 1 downto 0);
    trunc_ln224_2_fu_786_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(13 - 1 downto 0);
    trunc_ln224_3_fu_832_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(12 - 1 downto 0);
    trunc_ln224_4_fu_878_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(11 - 1 downto 0);
    trunc_ln224_5_fu_924_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(10 - 1 downto 0);
    trunc_ln224_6_fu_970_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(9 - 1 downto 0);
    trunc_ln224_7_fu_1016_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(8 - 1 downto 0);
    trunc_ln224_8_fu_1062_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(7 - 1 downto 0);
    trunc_ln224_9_fu_1086_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(6 - 1 downto 0);
    trunc_ln224_fu_707_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(15 - 1 downto 0);
    trunc_ln237_1_fu_1427_p1 <= add_ln862_fu_1303_p2(17 - 1 downto 0);
    trunc_ln237_2_fu_1453_p1 <= add_ln862_fu_1303_p2(16 - 1 downto 0);
    trunc_ln237_3_fu_1479_p1 <= add_ln862_fu_1303_p2(15 - 1 downto 0);
    trunc_ln237_4_fu_1505_p1 <= add_ln862_fu_1303_p2(14 - 1 downto 0);
    trunc_ln237_fu_1401_p1 <= add_ln862_fu_1303_p2(18 - 1 downto 0);
    trunc_ln809_fu_688_p1 <= abs_raw_signed_2_reg_1898_pp0_iter1_reg(16 - 1 downto 0);
    trunc_ln816_fu_349_p1 <= clz_fu_341_p3(6 - 1 downto 0);
    trunc_ln858_fu_1248_p1 <= x_norm_raw_72_fu_1230_p3(8 - 1 downto 0);
    x_norm_raw_49_fu_700_p3 <= 
        shifted_63_fu_691_p4 when (icmp_ln221_reg_1981(0) = '1') else 
        trunc_ln809_fu_688_p1;
    x_norm_raw_50_fu_718_p3 <= 
        shifted_64_fu_710_p3 when (icmp_ln223_reg_1987(0) = '1') else 
        x_norm_raw_49_fu_700_p3;
    x_norm_raw_51_fu_734_p3 <= 
        shifted_65_fu_725_p4 when (icmp_ln221_1_reg_1993(0) = '1') else 
        x_norm_raw_50_fu_718_p3;
    x_norm_raw_52_fu_752_p3 <= 
        shifted_66_fu_744_p3 when (icmp_ln223_1_reg_2000(0) = '1') else 
        x_norm_raw_51_fu_734_p3;
    x_norm_raw_53_fu_773_p3 <= 
        shifted_67_fu_764_p4 when (icmp_ln221_2_fu_759_p2(0) = '1') else 
        x_norm_raw_52_fu_752_p3;
    x_norm_raw_54_fu_797_p3 <= 
        shifted_68_fu_789_p3 when (icmp_ln223_2_fu_781_p2(0) = '1') else 
        x_norm_raw_53_fu_773_p3;
    x_norm_raw_55_fu_819_p3 <= 
        shifted_69_fu_810_p4 when (icmp_ln221_3_fu_805_p2(0) = '1') else 
        x_norm_raw_54_fu_797_p3;
    x_norm_raw_56_fu_865_p3 <= 
        shifted_fu_856_p4 when (icmp_ln221_4_fu_851_p2(0) = '1') else 
        x_norm_raw_fu_843_p3;
    x_norm_raw_57_fu_889_p3 <= 
        shifted_71_fu_881_p3 when (icmp_ln223_4_fu_873_p2(0) = '1') else 
        x_norm_raw_56_fu_865_p3;
    x_norm_raw_58_fu_911_p3 <= 
        shifted_72_fu_902_p4 when (icmp_ln221_5_fu_897_p2(0) = '1') else 
        x_norm_raw_57_fu_889_p3;
    x_norm_raw_59_fu_935_p3 <= 
        shifted_73_fu_927_p3 when (icmp_ln223_5_fu_919_p2(0) = '1') else 
        x_norm_raw_58_fu_911_p3;
    x_norm_raw_60_fu_957_p3 <= 
        shifted_74_fu_948_p4 when (icmp_ln221_6_fu_943_p2(0) = '1') else 
        x_norm_raw_59_fu_935_p3;
    x_norm_raw_61_fu_981_p3 <= 
        shifted_75_fu_973_p3 when (icmp_ln223_6_fu_965_p2(0) = '1') else 
        x_norm_raw_60_fu_957_p3;
    x_norm_raw_62_fu_1003_p3 <= 
        shifted_76_fu_994_p4 when (icmp_ln221_7_fu_989_p2(0) = '1') else 
        x_norm_raw_61_fu_981_p3;
    x_norm_raw_63_fu_1027_p3 <= 
        shifted_77_fu_1019_p3 when (icmp_ln223_7_fu_1011_p2(0) = '1') else 
        x_norm_raw_62_fu_1003_p3;
    x_norm_raw_64_fu_1049_p3 <= 
        shifted_78_fu_1040_p4 when (icmp_ln221_8_fu_1035_p2(0) = '1') else 
        x_norm_raw_63_fu_1027_p3;
    x_norm_raw_65_fu_1073_p3 <= 
        shifted_79_fu_1065_p3 when (icmp_ln223_8_fu_1057_p2(0) = '1') else 
        x_norm_raw_64_fu_1049_p3;
    x_norm_raw_66_fu_1097_p3 <= 
        shifted_80_fu_1089_p3 when (icmp_ln223_9_fu_1081_p2(0) = '1') else 
        x_norm_raw_65_fu_1073_p3;
    x_norm_raw_67_fu_1121_p3 <= 
        shifted_81_fu_1113_p3 when (icmp_ln223_10_fu_1105_p2(0) = '1') else 
        x_norm_raw_66_fu_1097_p3;
    x_norm_raw_68_fu_1145_p3 <= 
        shifted_82_fu_1137_p3 when (icmp_ln223_11_fu_1129_p2(0) = '1') else 
        x_norm_raw_67_fu_1121_p3;
    x_norm_raw_69_fu_1169_p3 <= 
        shifted_83_fu_1161_p3 when (icmp_ln223_12_fu_1153_p2(0) = '1') else 
        x_norm_raw_68_fu_1145_p3;
    x_norm_raw_70_fu_1193_p3 <= 
        shifted_84_fu_1185_p3 when (icmp_ln223_13_fu_1177_p2(0) = '1') else 
        x_norm_raw_69_fu_1169_p3;
    x_norm_raw_71_fu_1217_p3 <= 
        shifted_85_fu_1209_p3 when (icmp_ln223_14_fu_1201_p2(0) = '1') else 
        x_norm_raw_70_fu_1193_p3;
    x_norm_raw_72_fu_1230_p3 <= 
        ap_const_lv16_0 when (icmp_ln223_15_fu_1225_p2(0) = '1') else 
        x_norm_raw_71_fu_1217_p3;
    x_norm_raw_fu_843_p3 <= 
        shifted_70_fu_835_p3 when (icmp_ln223_3_fu_827_p2(0) = '1') else 
        x_norm_raw_55_fu_819_p3;
    xor_ln804_fu_1850_p2 <= (icmp_ln804_reg_1887_pp0_iter5_reg xor ap_const_lv1_1);
    zext_ln236_1_fu_1766_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln236_19_fu_1758_p3),22));
    zext_ln236_fu_1692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln236_14_fu_1684_p3),5));
    zext_ln834_1_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_58_fu_472_p4),9));
    zext_ln834_2_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_59_fu_485_p4),9));
    zext_ln834_3_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_60_fu_498_p4),9));
    zext_ln834_4_fu_520_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_61_fu_511_p4),9));
    zext_ln834_5_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_62_fu_524_p4),9));
    zext_ln834_6_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_63_fu_537_p4),9));
    zext_ln834_7_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_64_fu_550_p4),9));
    zext_ln834_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_57_fu_461_p3),9));
    zext_ln848_fu_1252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lut_idx_reg_2122),9));
    zext_ln859_1_fu_1297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(v0_reg_2143_pp0_iter5_reg),20));
    zext_ln859_fu_1255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lut_idx_reg_2122),64));
    zext_ln860_fu_1265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln860_fu_1259_p2),64));
end behav;
