// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mpc_fpga_top_opencl_sum8_P_MIX_raw (
        ap_ready,
        a0,
        a1,
        a2,
        a3,
        a4,
        a5,
        a6,
        a7,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [56:0] a0;
input  [56:0] a1;
input  [56:0] a2;
input  [56:0] a3;
input  [56:0] a4;
input  [56:0] a5;
input  [56:0] a6;
input  [56:0] a7;
output  [56:0] ap_return;
input   ap_rst;

wire   [56:0] add_ln218_1_fu_90_p2;
wire   [56:0] add_ln218_fu_84_p2;
wire   [56:0] add_ln218_5_fu_108_p2;
wire   [56:0] add_ln218_4_fu_102_p2;
wire   [56:0] add_ln218_6_fu_114_p2;
wire   [56:0] add_ln218_3_fu_96_p2;

assign add_ln218_1_fu_90_p2 = (a0 + a1);

assign add_ln218_3_fu_96_p2 = (add_ln218_1_fu_90_p2 + add_ln218_fu_84_p2);

assign add_ln218_4_fu_102_p2 = (a4 + a5);

assign add_ln218_5_fu_108_p2 = (a6 + a7);

assign add_ln218_6_fu_114_p2 = (add_ln218_5_fu_108_p2 + add_ln218_4_fu_102_p2);

assign add_ln218_fu_84_p2 = (a3 + a2);

assign ap_ready = 1'b1;

assign ap_return = (add_ln218_6_fu_114_p2 + add_ln218_3_fu_96_p2);

endmodule //mpc_fpga_top_opencl_sum8_P_MIX_raw
