// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mpc_fpga_top_opencl_fp_front_force_jacobians_fn (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C_eff_f,
        front_num,
        vx_safe,
        inv_D_f,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [25:0] C_eff_f;
input  [25:0] front_num;
input  [24:0] vx_safe;
input  [22:0] inv_D_f;
output  [25:0] ap_return_0;
output  [25:0] ap_return_1;
output  [25:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [24:0] vx_safe_read_reg_237;
reg  signed [22:0] inv_D_f_read_reg_247;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [42:0] sext_ln671_41_fu_175_p1;
reg  signed [42:0] sext_ln671_41_reg_283;
wire    ap_CS_fsm_state5;
wire  signed [42:0] sext_ln671_43_fu_180_p1;
wire  signed [42:0] sext_ln671_42_fu_195_p1;
wire    ap_CS_fsm_state6;
wire  signed [42:0] sext_ln671_44_fu_216_p1;
wire    ap_CS_fsm_state7;
reg   [25:0] product_q_55_reg_303;
wire    ap_CS_fsm_state8;
reg   [25:0] product_q_54_reg_308;
wire    ap_CS_fsm_state9;
reg   [25:0] ap_port_reg_C_eff_f;
reg  signed [25:0] ap_port_reg_front_num;
reg   [22:0] ap_port_reg_inv_D_f;
wire   [22:0] grp_fu_86_p0;
wire   [24:0] grp_fu_90_p1;
reg  signed [25:0] grp_fu_98_p0;
reg  signed [25:0] grp_fu_98_p1;
wire   [42:0] grp_fu_98_p2;
wire    ap_CS_fsm_state10;
wire   [24:0] grp_fu_116_p0;
wire   [15:0] grp_fu_116_p1;
wire  signed [22:0] sext_ln671_39_fu_126_p0;
wire   [39:0] grp_fu_116_p2;
wire   [22:0] product_q_s_fu_144_p4;
wire   [47:0] grp_fu_90_p2;
wire   [25:0] product_q_fu_159_p4;
wire   [25:0] daf_dvy_fu_169_p2;
wire   [48:0] grp_fu_94_p2;
wire   [25:0] product_q_52_fu_185_p4;
wire   [45:0] grp_fu_86_p2;
wire   [25:0] product_q_53_fu_200_p4;
wire   [25:0] daf_dom_fu_210_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire   [39:0] grp_fu_116_p00;
wire   [45:0] grp_fu_86_p00;
wire   [47:0] grp_fu_90_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
end

mpc_fpga_top_opencl_mul_23ns_23s_46_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 46 ))
mul_23ns_23s_46_4_1_U339(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_86_p0),
    .din1(inv_D_f_read_reg_247),
    .ce(1'b1),
    .dout(grp_fu_86_p2)
);

mpc_fpga_top_opencl_mul_23s_25ns_48_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 48 ))
mul_23s_25ns_48_4_1_U340(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln671_39_fu_126_p0),
    .din1(grp_fu_90_p1),
    .ce(1'b1),
    .dout(grp_fu_90_p2)
);

mpc_fpga_top_opencl_mul_26s_23s_49_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 49 ))
mul_26s_23s_49_4_1_U341(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_port_reg_front_num),
    .din1(inv_D_f_read_reg_247),
    .ce(1'b1),
    .dout(grp_fu_94_p2)
);

mpc_fpga_top_opencl_mul_26s_26s_43_4_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 43 ))
mul_26s_26s_43_4_1_x_U342(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_98_p0),
    .din1(grp_fu_98_p1),
    .ce(1'b1),
    .dout(grp_fu_98_p2)
);

mpc_fpga_top_opencl_mul_25ns_16ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 40 ))
mul_25ns_16ns_40_4_1_U343(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_116_p0),
    .din1(grp_fu_116_p1),
    .ce(1'b1),
    .dout(grp_fu_116_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ap_port_reg_C_eff_f <= C_eff_f;
        ap_port_reg_front_num <= front_num;
        ap_port_reg_inv_D_f <= inv_D_f;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        inv_D_f_read_reg_247 <= ap_port_reg_inv_D_f;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        product_q_54_reg_308 <= {{grp_fu_98_p2[42:17]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        product_q_55_reg_303 <= {{grp_fu_98_p2[42:17]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sext_ln671_41_reg_283 <= sext_ln671_41_fu_175_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        vx_safe_read_reg_237 <= vx_safe;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_98_p0 = sext_ln671_44_fu_216_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_98_p0 = sext_ln671_42_fu_195_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_98_p0 = sext_ln671_43_fu_180_p1;
    end else begin
        grp_fu_98_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_98_p1 = sext_ln671_41_reg_283;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_98_p1 = sext_ln671_41_fu_175_p1;
    end else begin
        grp_fu_98_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = product_q_54_reg_308;

assign ap_return_1 = product_q_55_reg_303;

assign ap_return_2 = {{grp_fu_98_p2[42:17]}};

assign daf_dom_fu_210_p2 = (26'd0 - product_q_53_fu_200_p4);

assign daf_dvy_fu_169_p2 = (26'd0 - product_q_fu_159_p4);

assign grp_fu_116_p0 = grp_fu_116_p00;

assign grp_fu_116_p00 = vx_safe;

assign grp_fu_116_p1 = 40'd21757;

assign grp_fu_86_p0 = grp_fu_86_p00;

assign grp_fu_86_p00 = product_q_s_fu_144_p4;

assign grp_fu_90_p1 = grp_fu_90_p10;

assign grp_fu_90_p10 = vx_safe_read_reg_237;

assign product_q_52_fu_185_p4 = {{grp_fu_94_p2[42:17]}};

assign product_q_53_fu_200_p4 = {{grp_fu_86_p2[42:17]}};

assign product_q_fu_159_p4 = {{grp_fu_90_p2[42:17]}};

assign product_q_s_fu_144_p4 = {{grp_fu_116_p2[39:17]}};

assign sext_ln671_39_fu_126_p0 = ap_port_reg_inv_D_f;

assign sext_ln671_41_fu_175_p1 = $signed(ap_port_reg_C_eff_f);

assign sext_ln671_42_fu_195_p1 = $signed(product_q_52_fu_185_p4);

assign sext_ln671_43_fu_180_p1 = $signed(daf_dvy_fu_169_p2);

assign sext_ln671_44_fu_216_p1 = $signed(daf_dom_fu_210_p2);

endmodule //mpc_fpga_top_opencl_fp_front_force_jacobians_fn
