// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mpc_fpga_top_opencl_mpc_compute_hls_Pipeline_VITIS_LOOP_364_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_0_0_010171165_reload,
        p_0_0_010171161_reload,
        p_0_0_010171157_reload,
        p_0_0_010171153_reload,
        p_0_0_010171149_reload,
        p_0_0_010171145_reload,
        p_0_0_010171141_reload,
        p_0_0_010171137_reload,
        p_0_0_010171133_reload,
        p_0_0_010171129_reload,
        p_0_0_010171125_reload,
        p_0_0_010171121_reload,
        p_0_0_010171117_reload,
        p_0_0_010171113_reload,
        p_0_0_010171109_reload,
        p_0_0_010171105_reload,
        p_0_0_010171101_reload,
        p_0_0_01017197_reload,
        p_0_0_01017193_reload,
        p_0_0_010171169_reload,
        p_0_0_010170167_reload,
        p_0_0_010170163_reload,
        p_0_0_010170159_reload,
        p_0_0_010170155_reload,
        p_0_0_010170151_reload,
        p_0_0_010170147_reload,
        p_0_0_010170143_reload,
        p_0_0_010170139_reload,
        p_0_0_010170135_reload,
        p_0_0_010170131_reload,
        p_0_0_010170127_reload,
        p_0_0_010170123_reload,
        p_0_0_010170119_reload,
        p_0_0_010170115_reload,
        p_0_0_010170111_reload,
        p_0_0_010170107_reload,
        p_0_0_010170103_reload,
        p_0_0_01017099_reload,
        p_0_0_01017095_reload,
        p_0_0_010170171_reload,
        wall_right_min_19_out,
        wall_right_min_19_out_ap_vld,
        wall_right_min_18_out,
        wall_right_min_18_out_ap_vld,
        wall_right_min_17_out,
        wall_right_min_17_out_ap_vld,
        wall_right_min_16_out,
        wall_right_min_16_out_ap_vld,
        wall_right_min_15_out,
        wall_right_min_15_out_ap_vld,
        wall_right_min_14_out,
        wall_right_min_14_out_ap_vld,
        wall_right_min_13_out,
        wall_right_min_13_out_ap_vld,
        wall_right_min_12_out,
        wall_right_min_12_out_ap_vld,
        wall_right_min_11_out,
        wall_right_min_11_out_ap_vld,
        wall_right_min_10_out,
        wall_right_min_10_out_ap_vld,
        wall_right_min_9_out,
        wall_right_min_9_out_ap_vld,
        wall_right_min_8_out,
        wall_right_min_8_out_ap_vld,
        wall_right_min_7_out,
        wall_right_min_7_out_ap_vld,
        wall_right_min_6_out,
        wall_right_min_6_out_ap_vld,
        wall_right_min_5_out,
        wall_right_min_5_out_ap_vld,
        wall_right_min_4_out,
        wall_right_min_4_out_ap_vld,
        wall_right_min_3_out,
        wall_right_min_3_out_ap_vld,
        wall_right_min_2_out,
        wall_right_min_2_out_ap_vld,
        wall_right_min_1_out,
        wall_right_min_1_out_ap_vld,
        wall_right_min_out,
        wall_right_min_out_ap_vld,
        wall_left_min_19_out,
        wall_left_min_19_out_ap_vld,
        wall_left_min_18_out,
        wall_left_min_18_out_ap_vld,
        wall_left_min_17_out,
        wall_left_min_17_out_ap_vld,
        wall_left_min_16_out,
        wall_left_min_16_out_ap_vld,
        wall_left_min_15_out,
        wall_left_min_15_out_ap_vld,
        wall_left_min_14_out,
        wall_left_min_14_out_ap_vld,
        wall_left_min_13_out,
        wall_left_min_13_out_ap_vld,
        wall_left_min_12_out,
        wall_left_min_12_out_ap_vld,
        wall_left_min_11_out,
        wall_left_min_11_out_ap_vld,
        wall_left_min_10_out,
        wall_left_min_10_out_ap_vld,
        wall_left_min_9_out,
        wall_left_min_9_out_ap_vld,
        wall_left_min_8_out,
        wall_left_min_8_out_ap_vld,
        wall_left_min_7_out,
        wall_left_min_7_out_ap_vld,
        wall_left_min_6_out,
        wall_left_min_6_out_ap_vld,
        wall_left_min_5_out,
        wall_left_min_5_out_ap_vld,
        wall_left_min_4_out,
        wall_left_min_4_out_ap_vld,
        wall_left_min_3_out,
        wall_left_min_3_out_ap_vld,
        wall_left_min_2_out,
        wall_left_min_2_out_ap_vld,
        wall_left_min_1_out,
        wall_left_min_1_out_ap_vld,
        wall_left_min_out,
        wall_left_min_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [25:0] p_0_0_010171165_reload;
input  [25:0] p_0_0_010171161_reload;
input  [25:0] p_0_0_010171157_reload;
input  [25:0] p_0_0_010171153_reload;
input  [25:0] p_0_0_010171149_reload;
input  [25:0] p_0_0_010171145_reload;
input  [25:0] p_0_0_010171141_reload;
input  [25:0] p_0_0_010171137_reload;
input  [25:0] p_0_0_010171133_reload;
input  [25:0] p_0_0_010171129_reload;
input  [25:0] p_0_0_010171125_reload;
input  [25:0] p_0_0_010171121_reload;
input  [25:0] p_0_0_010171117_reload;
input  [25:0] p_0_0_010171113_reload;
input  [25:0] p_0_0_010171109_reload;
input  [25:0] p_0_0_010171105_reload;
input  [25:0] p_0_0_010171101_reload;
input  [25:0] p_0_0_01017197_reload;
input  [25:0] p_0_0_01017193_reload;
input  [25:0] p_0_0_010171169_reload;
input  [25:0] p_0_0_010170167_reload;
input  [25:0] p_0_0_010170163_reload;
input  [25:0] p_0_0_010170159_reload;
input  [25:0] p_0_0_010170155_reload;
input  [25:0] p_0_0_010170151_reload;
input  [25:0] p_0_0_010170147_reload;
input  [25:0] p_0_0_010170143_reload;
input  [25:0] p_0_0_010170139_reload;
input  [25:0] p_0_0_010170135_reload;
input  [25:0] p_0_0_010170131_reload;
input  [25:0] p_0_0_010170127_reload;
input  [25:0] p_0_0_010170123_reload;
input  [25:0] p_0_0_010170119_reload;
input  [25:0] p_0_0_010170115_reload;
input  [25:0] p_0_0_010170111_reload;
input  [25:0] p_0_0_010170107_reload;
input  [25:0] p_0_0_010170103_reload;
input  [25:0] p_0_0_01017099_reload;
input  [25:0] p_0_0_01017095_reload;
input  [25:0] p_0_0_010170171_reload;
output  [25:0] wall_right_min_19_out;
output   wall_right_min_19_out_ap_vld;
output  [25:0] wall_right_min_18_out;
output   wall_right_min_18_out_ap_vld;
output  [25:0] wall_right_min_17_out;
output   wall_right_min_17_out_ap_vld;
output  [25:0] wall_right_min_16_out;
output   wall_right_min_16_out_ap_vld;
output  [25:0] wall_right_min_15_out;
output   wall_right_min_15_out_ap_vld;
output  [25:0] wall_right_min_14_out;
output   wall_right_min_14_out_ap_vld;
output  [25:0] wall_right_min_13_out;
output   wall_right_min_13_out_ap_vld;
output  [25:0] wall_right_min_12_out;
output   wall_right_min_12_out_ap_vld;
output  [25:0] wall_right_min_11_out;
output   wall_right_min_11_out_ap_vld;
output  [25:0] wall_right_min_10_out;
output   wall_right_min_10_out_ap_vld;
output  [25:0] wall_right_min_9_out;
output   wall_right_min_9_out_ap_vld;
output  [25:0] wall_right_min_8_out;
output   wall_right_min_8_out_ap_vld;
output  [25:0] wall_right_min_7_out;
output   wall_right_min_7_out_ap_vld;
output  [25:0] wall_right_min_6_out;
output   wall_right_min_6_out_ap_vld;
output  [25:0] wall_right_min_5_out;
output   wall_right_min_5_out_ap_vld;
output  [25:0] wall_right_min_4_out;
output   wall_right_min_4_out_ap_vld;
output  [25:0] wall_right_min_3_out;
output   wall_right_min_3_out_ap_vld;
output  [25:0] wall_right_min_2_out;
output   wall_right_min_2_out_ap_vld;
output  [25:0] wall_right_min_1_out;
output   wall_right_min_1_out_ap_vld;
output  [25:0] wall_right_min_out;
output   wall_right_min_out_ap_vld;
output  [25:0] wall_left_min_19_out;
output   wall_left_min_19_out_ap_vld;
output  [25:0] wall_left_min_18_out;
output   wall_left_min_18_out_ap_vld;
output  [25:0] wall_left_min_17_out;
output   wall_left_min_17_out_ap_vld;
output  [25:0] wall_left_min_16_out;
output   wall_left_min_16_out_ap_vld;
output  [25:0] wall_left_min_15_out;
output   wall_left_min_15_out_ap_vld;
output  [25:0] wall_left_min_14_out;
output   wall_left_min_14_out_ap_vld;
output  [25:0] wall_left_min_13_out;
output   wall_left_min_13_out_ap_vld;
output  [25:0] wall_left_min_12_out;
output   wall_left_min_12_out_ap_vld;
output  [25:0] wall_left_min_11_out;
output   wall_left_min_11_out_ap_vld;
output  [25:0] wall_left_min_10_out;
output   wall_left_min_10_out_ap_vld;
output  [25:0] wall_left_min_9_out;
output   wall_left_min_9_out_ap_vld;
output  [25:0] wall_left_min_8_out;
output   wall_left_min_8_out_ap_vld;
output  [25:0] wall_left_min_7_out;
output   wall_left_min_7_out_ap_vld;
output  [25:0] wall_left_min_6_out;
output   wall_left_min_6_out_ap_vld;
output  [25:0] wall_left_min_5_out;
output   wall_left_min_5_out_ap_vld;
output  [25:0] wall_left_min_4_out;
output   wall_left_min_4_out_ap_vld;
output  [25:0] wall_left_min_3_out;
output   wall_left_min_3_out_ap_vld;
output  [25:0] wall_left_min_2_out;
output   wall_left_min_2_out_ap_vld;
output  [25:0] wall_left_min_1_out;
output   wall_left_min_1_out_ap_vld;
output  [25:0] wall_left_min_out;
output   wall_left_min_out_ap_vld;

reg ap_idle;
reg wall_right_min_19_out_ap_vld;
reg wall_right_min_18_out_ap_vld;
reg wall_right_min_17_out_ap_vld;
reg wall_right_min_16_out_ap_vld;
reg wall_right_min_15_out_ap_vld;
reg wall_right_min_14_out_ap_vld;
reg wall_right_min_13_out_ap_vld;
reg wall_right_min_12_out_ap_vld;
reg wall_right_min_11_out_ap_vld;
reg wall_right_min_10_out_ap_vld;
reg wall_right_min_9_out_ap_vld;
reg wall_right_min_8_out_ap_vld;
reg wall_right_min_7_out_ap_vld;
reg wall_right_min_6_out_ap_vld;
reg wall_right_min_5_out_ap_vld;
reg wall_right_min_4_out_ap_vld;
reg wall_right_min_3_out_ap_vld;
reg wall_right_min_2_out_ap_vld;
reg wall_right_min_1_out_ap_vld;
reg wall_right_min_out_ap_vld;
reg wall_left_min_19_out_ap_vld;
reg wall_left_min_18_out_ap_vld;
reg wall_left_min_17_out_ap_vld;
reg wall_left_min_16_out_ap_vld;
reg wall_left_min_15_out_ap_vld;
reg wall_left_min_14_out_ap_vld;
reg wall_left_min_13_out_ap_vld;
reg wall_left_min_12_out_ap_vld;
reg wall_left_min_11_out_ap_vld;
reg wall_left_min_10_out_ap_vld;
reg wall_left_min_9_out_ap_vld;
reg wall_left_min_8_out_ap_vld;
reg wall_left_min_7_out_ap_vld;
reg wall_left_min_6_out_ap_vld;
reg wall_left_min_5_out_ap_vld;
reg wall_left_min_4_out_ap_vld;
reg wall_left_min_3_out_ap_vld;
reg wall_left_min_2_out_ap_vld;
reg wall_left_min_1_out_ap_vld;
reg wall_left_min_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln364_fu_966_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] k_reg_1831;
reg   [0:0] icmp_ln364_reg_1838;
wire    grp_compute_window_min_hls_fu_908_ap_start;
wire    grp_compute_window_min_hls_fu_908_ap_done;
wire    grp_compute_window_min_hls_fu_908_ap_idle;
wire    grp_compute_window_min_hls_fu_908_ap_ready;
wire   [25:0] grp_compute_window_min_hls_fu_908_ap_return;
wire    grp_compute_window_min_hls_fu_933_ap_start;
wire    grp_compute_window_min_hls_fu_933_ap_done;
wire    grp_compute_window_min_hls_fu_933_ap_idle;
wire    grp_compute_window_min_hls_fu_933_ap_ready;
wire   [25:0] grp_compute_window_min_hls_fu_933_ap_return;
reg    grp_compute_window_min_hls_fu_908_ap_start_reg;
wire    ap_block_pp0_stage0_ignoreCallOp95;
reg    grp_compute_window_min_hls_fu_933_ap_start_reg;
wire    ap_block_pp0_stage0_ignoreCallOp96;
reg   [4:0] k_2_fu_224;
wire   [4:0] add_ln364_fu_972_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_k;
wire    ap_block_pp0_stage0;
reg   [25:0] wall_left_min_fu_228;
reg    ap_predicate_pred473_state3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [25:0] wall_left_min_1_fu_232;
reg    ap_predicate_pred488_state3;
reg   [25:0] wall_left_min_2_fu_236;
reg    ap_predicate_pred497_state3;
reg   [25:0] wall_left_min_3_fu_240;
reg    ap_predicate_pred506_state3;
reg   [25:0] wall_left_min_4_fu_244;
reg    ap_predicate_pred515_state3;
reg   [25:0] wall_left_min_5_fu_248;
reg    ap_predicate_pred524_state3;
reg   [25:0] wall_left_min_6_fu_252;
reg    ap_predicate_pred533_state3;
reg   [25:0] wall_left_min_7_fu_256;
reg    ap_predicate_pred542_state3;
reg   [25:0] wall_left_min_8_fu_260;
reg    ap_predicate_pred551_state3;
reg   [25:0] wall_left_min_9_fu_264;
reg    ap_predicate_pred560_state3;
reg   [25:0] wall_left_min_10_fu_268;
reg    ap_predicate_pred569_state3;
reg   [25:0] wall_left_min_11_fu_272;
reg    ap_predicate_pred578_state3;
reg   [25:0] wall_left_min_12_fu_276;
reg    ap_predicate_pred587_state3;
reg   [25:0] wall_left_min_13_fu_280;
reg    ap_predicate_pred596_state3;
reg   [25:0] wall_left_min_14_fu_284;
reg    ap_predicate_pred605_state3;
reg   [25:0] wall_left_min_15_fu_288;
reg    ap_predicate_pred614_state3;
reg   [25:0] wall_left_min_16_fu_292;
reg    ap_predicate_pred623_state3;
reg   [25:0] wall_left_min_17_fu_296;
reg    ap_predicate_pred632_state3;
reg   [25:0] wall_left_min_18_fu_300;
reg    ap_predicate_pred641_state3;
reg   [25:0] wall_left_min_19_fu_304;
reg    ap_predicate_pred685_state3;
reg   [25:0] wall_right_min_fu_308;
reg   [25:0] wall_right_min_1_fu_312;
reg   [25:0] wall_right_min_2_fu_316;
reg   [25:0] wall_right_min_3_fu_320;
reg   [25:0] wall_right_min_4_fu_324;
reg   [25:0] wall_right_min_5_fu_328;
reg   [25:0] wall_right_min_6_fu_332;
reg   [25:0] wall_right_min_7_fu_336;
reg   [25:0] wall_right_min_8_fu_340;
reg   [25:0] wall_right_min_9_fu_344;
reg   [25:0] wall_right_min_10_fu_348;
reg   [25:0] wall_right_min_11_fu_352;
reg   [25:0] wall_right_min_12_fu_356;
reg   [25:0] wall_right_min_13_fu_360;
reg   [25:0] wall_right_min_14_fu_364;
reg   [25:0] wall_right_min_15_fu_368;
reg   [25:0] wall_right_min_16_fu_372;
reg   [25:0] wall_right_min_17_fu_376;
reg   [25:0] wall_right_min_18_fu_380;
reg   [25:0] wall_right_min_19_fu_384;
wire    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 grp_compute_window_min_hls_fu_908_ap_start_reg = 1'b0;
#0 grp_compute_window_min_hls_fu_933_ap_start_reg = 1'b0;
#0 k_2_fu_224 = 5'd0;
#0 wall_left_min_fu_228 = 26'd0;
#0 wall_left_min_1_fu_232 = 26'd0;
#0 wall_left_min_2_fu_236 = 26'd0;
#0 wall_left_min_3_fu_240 = 26'd0;
#0 wall_left_min_4_fu_244 = 26'd0;
#0 wall_left_min_5_fu_248 = 26'd0;
#0 wall_left_min_6_fu_252 = 26'd0;
#0 wall_left_min_7_fu_256 = 26'd0;
#0 wall_left_min_8_fu_260 = 26'd0;
#0 wall_left_min_9_fu_264 = 26'd0;
#0 wall_left_min_10_fu_268 = 26'd0;
#0 wall_left_min_11_fu_272 = 26'd0;
#0 wall_left_min_12_fu_276 = 26'd0;
#0 wall_left_min_13_fu_280 = 26'd0;
#0 wall_left_min_14_fu_284 = 26'd0;
#0 wall_left_min_15_fu_288 = 26'd0;
#0 wall_left_min_16_fu_292 = 26'd0;
#0 wall_left_min_17_fu_296 = 26'd0;
#0 wall_left_min_18_fu_300 = 26'd0;
#0 wall_left_min_19_fu_304 = 26'd0;
#0 wall_right_min_fu_308 = 26'd0;
#0 wall_right_min_1_fu_312 = 26'd0;
#0 wall_right_min_2_fu_316 = 26'd0;
#0 wall_right_min_3_fu_320 = 26'd0;
#0 wall_right_min_4_fu_324 = 26'd0;
#0 wall_right_min_5_fu_328 = 26'd0;
#0 wall_right_min_6_fu_332 = 26'd0;
#0 wall_right_min_7_fu_336 = 26'd0;
#0 wall_right_min_8_fu_340 = 26'd0;
#0 wall_right_min_9_fu_344 = 26'd0;
#0 wall_right_min_10_fu_348 = 26'd0;
#0 wall_right_min_11_fu_352 = 26'd0;
#0 wall_right_min_12_fu_356 = 26'd0;
#0 wall_right_min_13_fu_360 = 26'd0;
#0 wall_right_min_14_fu_364 = 26'd0;
#0 wall_right_min_15_fu_368 = 26'd0;
#0 wall_right_min_16_fu_372 = 26'd0;
#0 wall_right_min_17_fu_376 = 26'd0;
#0 wall_right_min_18_fu_380 = 26'd0;
#0 wall_right_min_19_fu_384 = 26'd0;
#0 ap_done_reg = 1'b0;
end

mpc_fpga_top_opencl_compute_window_min_hls grp_compute_window_min_hls_fu_908(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_window_min_hls_fu_908_ap_start),
    .ap_done(grp_compute_window_min_hls_fu_908_ap_done),
    .ap_idle(grp_compute_window_min_hls_fu_908_ap_idle),
    .ap_ready(grp_compute_window_min_hls_fu_908_ap_ready),
    .ref_wall_0_val(p_0_0_010171165_reload),
    .ref_wall_1_val(p_0_0_010171161_reload),
    .ref_wall_2_val(p_0_0_010171157_reload),
    .ref_wall_3_val(p_0_0_010171153_reload),
    .ref_wall_4_val(p_0_0_010171149_reload),
    .ref_wall_5_val(p_0_0_010171145_reload),
    .ref_wall_6_val(p_0_0_010171141_reload),
    .ref_wall_7_val(p_0_0_010171137_reload),
    .ref_wall_8_val(p_0_0_010171133_reload),
    .ref_wall_9_val(p_0_0_010171129_reload),
    .ref_wall_10_val(p_0_0_010171125_reload),
    .ref_wall_11_val(p_0_0_010171121_reload),
    .ref_wall_12_val(p_0_0_010171117_reload),
    .ref_wall_13_val(p_0_0_010171113_reload),
    .ref_wall_14_val(p_0_0_010171109_reload),
    .ref_wall_15_val(p_0_0_010171105_reload),
    .ref_wall_16_val(p_0_0_010171101_reload),
    .ref_wall_17_val(p_0_0_01017197_reload),
    .ref_wall_18_val(p_0_0_01017193_reload),
    .ref_wall_19_val(p_0_0_010171169_reload),
    .center_idx(k_reg_1831),
    .ap_return(grp_compute_window_min_hls_fu_908_ap_return)
);

mpc_fpga_top_opencl_compute_window_min_hls grp_compute_window_min_hls_fu_933(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_window_min_hls_fu_933_ap_start),
    .ap_done(grp_compute_window_min_hls_fu_933_ap_done),
    .ap_idle(grp_compute_window_min_hls_fu_933_ap_idle),
    .ap_ready(grp_compute_window_min_hls_fu_933_ap_ready),
    .ref_wall_0_val(p_0_0_010170167_reload),
    .ref_wall_1_val(p_0_0_010170163_reload),
    .ref_wall_2_val(p_0_0_010170159_reload),
    .ref_wall_3_val(p_0_0_010170155_reload),
    .ref_wall_4_val(p_0_0_010170151_reload),
    .ref_wall_5_val(p_0_0_010170147_reload),
    .ref_wall_6_val(p_0_0_010170143_reload),
    .ref_wall_7_val(p_0_0_010170139_reload),
    .ref_wall_8_val(p_0_0_010170135_reload),
    .ref_wall_9_val(p_0_0_010170131_reload),
    .ref_wall_10_val(p_0_0_010170127_reload),
    .ref_wall_11_val(p_0_0_010170123_reload),
    .ref_wall_12_val(p_0_0_010170119_reload),
    .ref_wall_13_val(p_0_0_010170115_reload),
    .ref_wall_14_val(p_0_0_010170111_reload),
    .ref_wall_15_val(p_0_0_010170107_reload),
    .ref_wall_16_val(p_0_0_010170103_reload),
    .ref_wall_17_val(p_0_0_01017099_reload),
    .ref_wall_18_val(p_0_0_01017095_reload),
    .ref_wall_19_val(p_0_0_010170171_reload),
    .center_idx(k_reg_1831),
    .ap_return(grp_compute_window_min_hls_fu_933_ap_return)
);

mpc_fpga_top_opencl_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_window_min_hls_fu_908_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln364_fu_966_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_compute_window_min_hls_fu_908_ap_start_reg <= 1'b1;
        end else if ((grp_compute_window_min_hls_fu_908_ap_ready == 1'b1)) begin
            grp_compute_window_min_hls_fu_908_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_window_min_hls_fu_933_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln364_fu_966_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_compute_window_min_hls_fu_933_ap_start_reg <= 1'b1;
        end else if ((grp_compute_window_min_hls_fu_933_ap_ready == 1'b1)) begin
            grp_compute_window_min_hls_fu_933_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln364_fu_966_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_2_fu_224 <= add_ln364_fu_972_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_2_fu_224 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_predicate_pred473_state3 <= (k_reg_1831 == 5'd0);
        ap_predicate_pred488_state3 <= (k_reg_1831 == 5'd1);
        ap_predicate_pred497_state3 <= (k_reg_1831 == 5'd2);
        ap_predicate_pred506_state3 <= (k_reg_1831 == 5'd3);
        ap_predicate_pred515_state3 <= (k_reg_1831 == 5'd4);
        ap_predicate_pred524_state3 <= (k_reg_1831 == 5'd5);
        ap_predicate_pred533_state3 <= (k_reg_1831 == 5'd6);
        ap_predicate_pred542_state3 <= (k_reg_1831 == 5'd7);
        ap_predicate_pred551_state3 <= (k_reg_1831 == 5'd8);
        ap_predicate_pred560_state3 <= (k_reg_1831 == 5'd9);
        ap_predicate_pred569_state3 <= (k_reg_1831 == 5'd10);
        ap_predicate_pred578_state3 <= (k_reg_1831 == 5'd11);
        ap_predicate_pred587_state3 <= (k_reg_1831 == 5'd12);
        ap_predicate_pred596_state3 <= (k_reg_1831 == 5'd13);
        ap_predicate_pred605_state3 <= (k_reg_1831 == 5'd14);
        ap_predicate_pred614_state3 <= (k_reg_1831 == 5'd15);
        ap_predicate_pred623_state3 <= (k_reg_1831 == 5'd16);
        ap_predicate_pred632_state3 <= (k_reg_1831 == 5'd17);
        ap_predicate_pred641_state3 <= (k_reg_1831 == 5'd18);
        ap_predicate_pred685_state3 <= (~(k_reg_1831 == 5'd18) & ~(k_reg_1831 == 5'd17) & ~(k_reg_1831 == 5'd16) & ~(k_reg_1831 == 5'd15) & ~(k_reg_1831 == 5'd14) & ~(k_reg_1831 == 5'd13) & ~(k_reg_1831 == 5'd12) & ~(k_reg_1831 == 5'd11) & ~(k_reg_1831 == 5'd10) & ~(k_reg_1831 == 5'd9) & ~(k_reg_1831 == 5'd8) & ~(k_reg_1831 == 5'd7) & ~(k_reg_1831 == 5'd6) & ~(k_reg_1831 == 5'd5) & ~(k_reg_1831 == 5'd4) & ~(k_reg_1831 == 5'd3) & ~(k_reg_1831 == 5'd2) & ~(k_reg_1831 == 5'd1) & ~(k_reg_1831 == 5'd0));
        icmp_ln364_reg_1838 <= icmp_ln364_fu_966_p2;
        k_reg_1831 <= ap_sig_allocacmp_k;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred569_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_10_fu_268 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_10_fu_348 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred578_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_11_fu_272 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_11_fu_352 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred587_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_12_fu_276 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_12_fu_356 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred596_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_13_fu_280 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_13_fu_360 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred605_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_14_fu_284 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_14_fu_364 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred614_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_15_fu_288 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_15_fu_368 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred623_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_16_fu_292 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_16_fu_372 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred632_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_17_fu_296 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_17_fu_376 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred641_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_18_fu_300 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_18_fu_380 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred685_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_19_fu_304 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_19_fu_384 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred488_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_1_fu_232 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_1_fu_312 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred497_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_2_fu_236 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_2_fu_316 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred506_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_3_fu_240 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_3_fu_320 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred515_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_4_fu_244 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_4_fu_324 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred524_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_5_fu_248 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_5_fu_328 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred533_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_6_fu_252 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_6_fu_332 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred542_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_7_fu_256 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_7_fu_336 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred551_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_8_fu_260 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_8_fu_340 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred560_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_9_fu_264 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_9_fu_344 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred473_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        wall_left_min_fu_228 <= grp_compute_window_min_hls_fu_908_ap_return;
        wall_right_min_fu_308 <= grp_compute_window_min_hls_fu_933_ap_return;
    end
end

always @ (*) begin
    if (((icmp_ln364_fu_966_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k = 5'd0;
    end else begin
        ap_sig_allocacmp_k = k_2_fu_224;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_10_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_11_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_12_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_13_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_14_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_15_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_16_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_17_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_18_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_19_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_1_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_2_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_3_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_4_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_5_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_6_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_7_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_8_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_9_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_left_min_out_ap_vld = 1'b1;
    end else begin
        wall_left_min_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_10_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_11_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_12_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_13_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_14_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_15_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_16_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_17_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_18_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_19_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_1_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_2_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_3_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_4_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_5_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_6_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_7_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_8_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_9_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln364_reg_1838 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wall_right_min_out_ap_vld = 1'b1;
    end else begin
        wall_right_min_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln364_fu_972_p2 = (ap_sig_allocacmp_k + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp95 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp96 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_compute_window_min_hls_fu_908_ap_start = grp_compute_window_min_hls_fu_908_ap_start_reg;

assign grp_compute_window_min_hls_fu_933_ap_start = grp_compute_window_min_hls_fu_933_ap_start_reg;

assign icmp_ln364_fu_966_p2 = ((ap_sig_allocacmp_k == 5'd20) ? 1'b1 : 1'b0);

assign wall_left_min_10_out = wall_left_min_10_fu_268;

assign wall_left_min_11_out = wall_left_min_11_fu_272;

assign wall_left_min_12_out = wall_left_min_12_fu_276;

assign wall_left_min_13_out = wall_left_min_13_fu_280;

assign wall_left_min_14_out = wall_left_min_14_fu_284;

assign wall_left_min_15_out = wall_left_min_15_fu_288;

assign wall_left_min_16_out = wall_left_min_16_fu_292;

assign wall_left_min_17_out = wall_left_min_17_fu_296;

assign wall_left_min_18_out = wall_left_min_18_fu_300;

assign wall_left_min_19_out = wall_left_min_19_fu_304;

assign wall_left_min_1_out = wall_left_min_1_fu_232;

assign wall_left_min_2_out = wall_left_min_2_fu_236;

assign wall_left_min_3_out = wall_left_min_3_fu_240;

assign wall_left_min_4_out = wall_left_min_4_fu_244;

assign wall_left_min_5_out = wall_left_min_5_fu_248;

assign wall_left_min_6_out = wall_left_min_6_fu_252;

assign wall_left_min_7_out = wall_left_min_7_fu_256;

assign wall_left_min_8_out = wall_left_min_8_fu_260;

assign wall_left_min_9_out = wall_left_min_9_fu_264;

assign wall_left_min_out = wall_left_min_fu_228;

assign wall_right_min_10_out = wall_right_min_10_fu_348;

assign wall_right_min_11_out = wall_right_min_11_fu_352;

assign wall_right_min_12_out = wall_right_min_12_fu_356;

assign wall_right_min_13_out = wall_right_min_13_fu_360;

assign wall_right_min_14_out = wall_right_min_14_fu_364;

assign wall_right_min_15_out = wall_right_min_15_fu_368;

assign wall_right_min_16_out = wall_right_min_16_fu_372;

assign wall_right_min_17_out = wall_right_min_17_fu_376;

assign wall_right_min_18_out = wall_right_min_18_fu_380;

assign wall_right_min_19_out = wall_right_min_19_fu_384;

assign wall_right_min_1_out = wall_right_min_1_fu_312;

assign wall_right_min_2_out = wall_right_min_2_fu_316;

assign wall_right_min_3_out = wall_right_min_3_fu_320;

assign wall_right_min_4_out = wall_right_min_4_fu_324;

assign wall_right_min_5_out = wall_right_min_5_fu_328;

assign wall_right_min_6_out = wall_right_min_6_fu_332;

assign wall_right_min_7_out = wall_right_min_7_fu_336;

assign wall_right_min_8_out = wall_right_min_8_fu_340;

assign wall_right_min_9_out = wall_right_min_9_fu_344;

assign wall_right_min_out = wall_right_min_fu_308;

endmodule //mpc_fpga_top_opencl_mpc_compute_hls_Pipeline_VITIS_LOOP_364_2
