[hls]
relative_roots=/home/akselmo/Documents/GitHub/BachelorProject/FPGA_Implementations/MPC_FPGA_Kria/MPC_FPGA
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=riccati_backward_pass/S dim=1 type=complete variable=S
syn.directive.array_partition=riccati_backward_pass/Si dim=1 type=complete variable=Si
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_356_1 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_366_2 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1203_6 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1215_9 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1183_1 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1195_4 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1305_17 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1301_16 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1282_14 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1246_12 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1395_20 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1337_19 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=riccati_backward_pass/VITIS_LOOP_726_7  
syn.directive.loop_flatten=riccati_backward_pass/VITIS_LOOP_831_12  


