[hls]
relative_roots=/home/akselmo/Documents/GitHub/BachelorProject/FPGA_Implementations/MPC_FPGA_Kria/MPC_FPGA
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=riccati_backward_pass/S dim=1 type=complete variable=S
syn.directive.array_partition=riccati_backward_pass/Si dim=1 type=complete variable=Si
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=riccati_backward_pass/VITIS_LOOP_848_14 
syn.directive.pipeline=riccati_backward_pass/VITIS_LOOP_742_9 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_354_1 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_364_2 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1222_6 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1234_9 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1202_1 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1214_4 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1324_17 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1320_16 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1301_14 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1265_12 
syn.directive.pipeline=mpc_compute_hls/VITIS_LOOP_1362_19 


