# Inferred from syn.array_partition.complete_threshold=4
set_directive_array_partition riccati_backward_pass/S -dim=1 -type=complete S
set_directive_array_partition riccati_backward_pass/Si -dim=1 -type=complete Si
# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline riccati_backward_pass/VITIS_LOOP_848_14
set_directive_pipeline riccati_backward_pass/VITIS_LOOP_742_9
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_354_1
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_364_2
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1222_6
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1234_9
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1202_1
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1214_4
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1324_17
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1320_16
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1301_14
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1265_12
set_directive_pipeline mpc_compute_hls/VITIS_LOOP_1362_19
