set(_AMENT_PACKAGE_NAME "mpc_f1_10th")
set(mpc_f1_10th_VERSION "0.1.0")
set(mpc_f1_10th_MAINTAINER "Jonathan <jonathan@example.com>")
set(mpc_f1_10th_BUILD_DEPENDS "rosidl_default_generators" "rclc" "rcl" "rcutils" "nav_msgs" "geometry_msgs" "sensor_msgs" "ackermann_msgs" "builtin_interfaces" "std_msgs")
set(mpc_f1_10th_BUILDTOOL_DEPENDS "ament_cmake")
set(mpc_f1_10th_BUILD_EXPORT_DEPENDS "rclc" "rcl" "rcutils" "nav_msgs" "geometry_msgs" "sensor_msgs" "ackermann_msgs" "builtin_interfaces" "std_msgs")
set(mpc_f1_10th_BUILDTOOL_EXPORT_DEPENDS )
set(mpc_f1_10th_EXEC_DEPENDS "rosidl_default_runtime" "f1tenth_planning" "rclc" "rcl" "rcutils" "nav_msgs" "geometry_msgs" "sensor_msgs" "ackermann_msgs" "builtin_interfaces" "std_msgs")
set(mpc_f1_10th_TEST_DEPENDS )
set(mpc_f1_10th_GROUP_DEPENDS )
set(mpc_f1_10th_MEMBER_OF_GROUPS )
set(mpc_f1_10th_DEPRECATED "")
set(mpc_f1_10th_EXPORT_TAGS)
list(APPEND mpc_f1_10th_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
