recording:
  record_all_topics: true
  include_hidden_topics: true
  qos_profile_overrides: config/bag_qos_overrides.yaml
required:
  command_audit:
  - /sensors/imu/raw
  - /sensors/core
  - /ego_racecar/odom
  - /scan
  - /erpm_calibration/motor_mode
  - /erpm_calibration/motor_selector_status
  - /erpm_calibration/motor_raw_speed
  - /erpm_calibration/motor_raw_brake
  - /erpm_calibration/motor_raw_current
  - /erpm_calibration/motor_selected_speed
  - /erpm_calibration/motor_selected_current
  - /erpm_calibration/motor_selected_brake
  - /commands/motor/speed
  - /commands/motor/current
  - /commands/motor/brake
  - /erpm_calibration/event
  raw_erpm:
  - /sensors/imu/raw
  - /sensors/core
  - /ego_racecar/odom
  - /scan
  - /tf_static
  - /erpm_calibration/motor_mode
  - /erpm_calibration/motor_selector_status
  - /erpm_calibration/motor_raw_speed
  - /erpm_calibration/motor_selected_speed
  - /erpm_calibration/motor_selected_current
  - /erpm_calibration/motor_selected_brake
  - /commands/motor/speed
  - /commands/motor/current
  - /commands/motor/brake
  - /commands/servo/position
  - /sensors/servo_position_command
  - /erpm_calibration/event
  ackermann_vel:
  - /sensors/imu/raw
  - /sensors/core
  - /ego_racecar/odom
  - /scan
  - /tf_static
  - /drive
  - /ackermann_cmd
  - /erpm_calibration/motor_mode
  - /erpm_calibration/motor_selector_status
  - /erpm_calibration/motor_from_ackermann/speed
  - /erpm_calibration/motor_selected_speed
  - /commands/motor/speed
  - /commands/servo/position
  - /sensors/servo_position_command
  - /erpm_calibration/event
  raw_current:
  - /sensors/imu/raw
  - /sensors/core
  - /ego_racecar/odom
  - /scan
  - /tf_static
  - /erpm_calibration/motor_mode
  - /erpm_calibration/motor_selector_status
  - /erpm_calibration/motor_raw_speed
  - /erpm_calibration/motor_raw_current
  - /erpm_calibration/motor_raw_brake
  - /erpm_calibration/motor_selected_speed
  - /erpm_calibration/motor_selected_current
  - /erpm_calibration/motor_selected_brake
  - /commands/motor/speed
  - /commands/motor/current
  - /commands/motor/brake
  - /commands/servo/position
  - /sensors/servo_position_command
  - /erpm_calibration/event
  ackermann_accel:
  - /sensors/imu/raw
  - /sensors/core
  - /ego_racecar/odom
  - /scan
  - /tf_static
  - /drive
  - /ackermann_cmd
  - /erpm_calibration/motor_mode
  - /erpm_calibration/motor_selector_status
  - /erpm_calibration/motor_raw_speed
  - /erpm_calibration/motor_from_ackermann/current
  - /erpm_calibration/motor_from_ackermann/brake
  - /erpm_calibration/motor_selected_speed
  - /erpm_calibration/motor_selected_current
  - /erpm_calibration/motor_selected_brake
  - /commands/motor/speed
  - /commands/motor/current
  - /commands/motor/brake
  - /commands/servo/position
  - /sensors/servo_position_command
  - /erpm_calibration/event
redundancy_topics:
- /tf
- /parameter_events
- /diagnostics
- /diagnostics_agg
- /rosout
- /clock
- /erpm_calibration/motor_from_ackermann/speed
- /erpm_calibration/motor_from_ackermann/current
- /erpm_calibration/motor_from_ackermann/brake
