ros2_udp_sender:
  ros__parameters:
    trajectory_file: "/BachelorProject/f1tenth_planning/trajectories/my_track_raceline.csv"
    odom_topic: "/ego_racecar/odom"
    servo_topic: "/sensors/servo_position_command"
    wheelbase: 0.324
    servo_gain: -0.7284
    servo_offset: 0.55
    steering_correction_c2: 0.589566
    steering_correction_c1: 0.918061
    steering_correction_c0: 0.001490
    forward_lookahead: 3
    horizon: 20
    interpolate_horizon: true
    horizon_step_m: 0.0
    dest_ip: "192.168.50.182"
    dest_port: 49000
