-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mpc_fpga_top_opencl_sum8_P_MIX_raw is
port (
    ap_ready : OUT STD_LOGIC;
    a0 : IN STD_LOGIC_VECTOR (56 downto 0);
    a1 : IN STD_LOGIC_VECTOR (56 downto 0);
    a2 : IN STD_LOGIC_VECTOR (56 downto 0);
    a3 : IN STD_LOGIC_VECTOR (56 downto 0);
    a4 : IN STD_LOGIC_VECTOR (56 downto 0);
    a5 : IN STD_LOGIC_VECTOR (56 downto 0);
    a6 : IN STD_LOGIC_VECTOR (56 downto 0);
    a7 : IN STD_LOGIC_VECTOR (56 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (56 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of mpc_fpga_top_opencl_sum8_P_MIX_raw is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal add_ln218_1_fu_90_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln218_fu_84_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln218_5_fu_108_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln218_4_fu_102_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln218_6_fu_114_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln218_3_fu_96_p2 : STD_LOGIC_VECTOR (56 downto 0);


begin



    add_ln218_1_fu_90_p2 <= std_logic_vector(unsigned(a0) + unsigned(a1));
    add_ln218_3_fu_96_p2 <= std_logic_vector(unsigned(add_ln218_1_fu_90_p2) + unsigned(add_ln218_fu_84_p2));
    add_ln218_4_fu_102_p2 <= std_logic_vector(unsigned(a4) + unsigned(a5));
    add_ln218_5_fu_108_p2 <= std_logic_vector(unsigned(a6) + unsigned(a7));
    add_ln218_6_fu_114_p2 <= std_logic_vector(unsigned(add_ln218_5_fu_108_p2) + unsigned(add_ln218_4_fu_102_p2));
    add_ln218_fu_84_p2 <= std_logic_vector(unsigned(a3) + unsigned(a2));
    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(add_ln218_6_fu_114_p2) + unsigned(add_ln218_3_fu_96_p2));
end behav;
