-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mpc_fpga_top_opencl_invert_2x2_qp_hls is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (25 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (25 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (25 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (25 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (25 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (25 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (25 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (25 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (25 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fp_recip_fu_3707_p_din1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fp_recip_fu_3707_p_dout0 : IN STD_LOGIC_VECTOR (16 downto 0);
    grp_fu_15620_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_15620_p_din1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_15620_p_dout0 : IN STD_LOGIC_VECTOR (39 downto 0);
    grp_fu_15620_p_ce : OUT STD_LOGIC;
    grp_fu_15624_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_15624_p_din1 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_15624_p_dout0 : IN STD_LOGIC_VECTOR (39 downto 0);
    grp_fu_15624_p_ce : OUT STD_LOGIC );
end;


architecture behav of mpc_fpga_top_opencl_invert_2x2_qp_hls is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv26_3FFFFFC : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111111111100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal scale_shift_fu_395_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal scale_shift_reg_634 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln359_fu_419_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln359_reg_639 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal s00_sc_fu_422_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal s00_sc_reg_646 : STD_LOGIC_VECTOR (25 downto 0);
    signal s01_sc_fu_427_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal s01_sc_reg_651 : STD_LOGIC_VECTOR (25 downto 0);
    signal s11_sc_fu_432_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal s11_sc_reg_656 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln156_34_fu_437_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln156_36_fu_442_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln156_37_fu_447_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal det_raw_fu_459_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal det_raw_reg_677 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln383_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln383_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sext_ln156_fu_497_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln156_reg_706 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln156_35_fu_500_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln156_35_reg_711 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln156_38_fu_503_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_phi_mux_phi_ln405_phi_fu_151_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal phi_ln405_reg_148 : STD_LOGIC_VECTOR (25 downto 0);
    signal ashr_ln401_fu_568_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_phi_mux_phi_ln405_1_phi_fu_160_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal phi_ln405_1_reg_157 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_phi_mux_phi_ln405_2_phi_fu_169_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal phi_ln405_2_reg_166 : STD_LOGIC_VECTOR (25 downto 0);
    signal ashr_ln400_fu_562_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_phi_mux_phi_ln405_3_phi_fu_178_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal phi_ln405_3_reg_175 : STD_LOGIC_VECTOR (25 downto 0);
    signal ashr_ln403_fu_575_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_phi_mux_retval_0_phi_fu_188_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_reg_184 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_abs_1_fu_221_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_fu_213_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_abs_fu_225_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal t_1_fu_247_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_49_fu_239_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_fu_251_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal t_2_fu_257_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal max_abs_2_fu_231_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln344_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_3_fu_287_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_50_fu_279_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_4_fu_291_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal t_5_fu_297_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal max_abs_3_fu_271_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln354_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_abs_4_fu_311_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_54_fu_343_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_319_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_327_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln362_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln362_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_fu_335_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln362_1_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln362_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln362_1_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal scale_shift_fu_395_p8 : STD_LOGIC_VECTOR (2 downto 0);
    signal scale_shift_fu_395_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal scale_shift_fu_395_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal det_mul_raw_fu_453_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_55_fu_475_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln383_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln383_1_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_507_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_507_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal a_126_fu_512_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_521_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_527_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_527_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_507_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal grp_fu_521_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal grp_fu_527_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal si00_sc_fu_532_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal si01_sc_fu_542_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal si11_sc_fu_552_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal select_ln405_fu_581_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal scale_shift_fu_395_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal scale_shift_fu_395_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal scale_shift_fu_395_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal scale_shift_fu_395_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mpc_fpga_top_opencl_fp_recip IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x : IN STD_LOGIC_VECTOR (25 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component mpc_fpga_top_opencl_mul_26s_26s_40_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (25 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component mpc_fpga_top_opencl_sparsemux_9_3_3_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (2 downto 0);
        din3 : IN STD_LOGIC_VECTOR (2 downto 0);
        def : IN STD_LOGIC_VECTOR (2 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component mpc_fpga_top_opencl_mul_17s_26s_43_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (25 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (42 downto 0) );
    end component;



begin
    sparsemux_9_3_3_1_1_U807 : component mpc_fpga_top_opencl_sparsemux_9_3_3_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 3,
        CASE1 => "010",
        din1_WIDTH => 3,
        CASE2 => "001",
        din2_WIDTH => 3,
        CASE3 => "000",
        din3_WIDTH => 3,
        def_WIDTH => 3,
        sel_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => ap_const_lv3_4,
        din1 => ap_const_lv3_3,
        din2 => ap_const_lv3_2,
        din3 => scale_shift_fu_395_p8,
        def => scale_shift_fu_395_p9,
        sel => scale_shift_fu_395_p10,
        dout => scale_shift_fu_395_p11);

    mul_17s_26s_43_3_1_U808 : component mpc_fpga_top_opencl_mul_17s_26s_43_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 26,
        dout_WIDTH => 43)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_507_p0,
        din1 => grp_fu_507_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_507_p2);

    mul_17s_26s_43_3_1_U809 : component mpc_fpga_top_opencl_mul_17s_26s_43_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 26,
        dout_WIDTH => 43)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_521_p0,
        din1 => a_126_fu_512_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_521_p2);

    mul_17s_26s_43_3_1_U810 : component mpc_fpga_top_opencl_mul_17s_26s_43_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 26,
        dout_WIDTH => 43)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_527_p0,
        din1 => grp_fu_527_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_527_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_return_0_preg <= select_ln405_fu_581_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv26_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_return_1_preg <= ap_phi_mux_phi_ln405_2_phi_fu_169_p4;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv26_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_return_2_preg <= ap_phi_mux_phi_ln405_phi_fu_151_p4;
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv26_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_return_3_preg <= ap_phi_mux_phi_ln405_1_phi_fu_160_p4;
                end if; 
            end if;
        end if;
    end process;


    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg <= ap_const_lv26_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_return_4_preg <= ap_phi_mux_phi_ln405_3_phi_fu_178_p4;
                end if; 
            end if;
        end if;
    end process;


    phi_ln405_1_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
                phi_ln405_1_reg_157 <= ashr_ln401_fu_568_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_1 = and_ln383_reg_682))) then 
                phi_ln405_1_reg_157 <= p_read6;
            end if; 
        end if;
    end process;

    phi_ln405_2_reg_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
                phi_ln405_2_reg_166 <= ashr_ln400_fu_562_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_1 = and_ln383_reg_682))) then 
                phi_ln405_2_reg_166 <= p_read4;
            end if; 
        end if;
    end process;

    phi_ln405_3_reg_175_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
                phi_ln405_3_reg_175 <= ashr_ln403_fu_575_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_1 = and_ln383_reg_682))) then 
                phi_ln405_3_reg_175 <= p_read7;
            end if; 
        end if;
    end process;

    phi_ln405_reg_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
                phi_ln405_reg_148 <= ashr_ln401_fu_568_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_1 = and_ln383_reg_682))) then 
                phi_ln405_reg_148 <= p_read5;
            end if; 
        end if;
    end process;

    retval_0_reg_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
                retval_0_reg_184 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_1 = and_ln383_reg_682))) then 
                retval_0_reg_184 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                and_ln383_reg_682 <= and_ln383_fu_491_p2;
                det_raw_reg_677 <= det_mul_raw_fu_453_p2(39 downto 14);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                s00_sc_reg_646 <= s00_sc_fu_422_p2;
                s01_sc_reg_651 <= s01_sc_fu_427_p2;
                s11_sc_reg_656 <= s11_sc_fu_432_p2;
                    zext_ln359_reg_639(2 downto 0) <= zext_ln359_fu_419_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                scale_shift_reg_634 <= scale_shift_fu_395_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                sext_ln156_35_reg_711 <= sext_ln156_35_fu_500_p1;
                sext_ln156_reg_706 <= sext_ln156_fu_497_p1;
            end if;
        end if;
    end process;
    zext_ln359_reg_639(25 downto 3) <= "00000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, and_ln383_reg_682, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_1 = and_ln383_reg_682))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    a_126_fu_512_p2 <= std_logic_vector(unsigned(ap_const_lv26_0) - unsigned(s01_sc_reg_651));
    and_ln362_1_fu_379_p2 <= (xor_ln362_1_fu_373_p2 and tmp_53_fu_335_p3);
    and_ln362_fu_361_p2 <= (xor_ln362_fu_355_p2 and tmp_52_fu_327_p3);
    and_ln383_fu_491_p2 <= (icmp_ln383_fu_469_p2 and icmp_ln383_1_fu_485_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_phi_ln405_1_phi_fu_160_p4_assign_proc : process(and_ln383_reg_682, ashr_ln401_fu_568_p2, ap_CS_fsm_state14, phi_ln405_1_reg_157)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
            ap_phi_mux_phi_ln405_1_phi_fu_160_p4 <= ashr_ln401_fu_568_p2;
        else 
            ap_phi_mux_phi_ln405_1_phi_fu_160_p4 <= phi_ln405_1_reg_157;
        end if; 
    end process;


    ap_phi_mux_phi_ln405_2_phi_fu_169_p4_assign_proc : process(and_ln383_reg_682, ap_CS_fsm_state14, phi_ln405_2_reg_166, ashr_ln400_fu_562_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
            ap_phi_mux_phi_ln405_2_phi_fu_169_p4 <= ashr_ln400_fu_562_p2;
        else 
            ap_phi_mux_phi_ln405_2_phi_fu_169_p4 <= phi_ln405_2_reg_166;
        end if; 
    end process;


    ap_phi_mux_phi_ln405_3_phi_fu_178_p4_assign_proc : process(and_ln383_reg_682, ap_CS_fsm_state14, phi_ln405_3_reg_175, ashr_ln403_fu_575_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
            ap_phi_mux_phi_ln405_3_phi_fu_178_p4 <= ashr_ln403_fu_575_p2;
        else 
            ap_phi_mux_phi_ln405_3_phi_fu_178_p4 <= phi_ln405_3_reg_175;
        end if; 
    end process;


    ap_phi_mux_phi_ln405_phi_fu_151_p4_assign_proc : process(and_ln383_reg_682, phi_ln405_reg_148, ashr_ln401_fu_568_p2, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
            ap_phi_mux_phi_ln405_phi_fu_151_p4 <= ashr_ln401_fu_568_p2;
        else 
            ap_phi_mux_phi_ln405_phi_fu_151_p4 <= phi_ln405_reg_148;
        end if; 
    end process;


    ap_phi_mux_retval_0_phi_fu_188_p4_assign_proc : process(and_ln383_reg_682, ap_CS_fsm_state14, retval_0_reg_184)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_lv1_0 = and_ln383_reg_682))) then 
            ap_phi_mux_retval_0_phi_fu_188_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_retval_0_phi_fu_188_p4 <= retval_0_reg_184;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_state14, select_ln405_fu_581_p3, ap_return_0_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_return_0 <= select_ln405_fu_581_p3;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state14, ap_phi_mux_phi_ln405_2_phi_fu_169_p4, ap_return_1_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_return_1 <= ap_phi_mux_phi_ln405_2_phi_fu_169_p4;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_phi_mux_phi_ln405_phi_fu_151_p4, ap_CS_fsm_state14, ap_return_2_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_return_2 <= ap_phi_mux_phi_ln405_phi_fu_151_p4;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_CS_fsm_state14, ap_phi_mux_phi_ln405_1_phi_fu_160_p4, ap_return_3_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_return_3 <= ap_phi_mux_phi_ln405_1_phi_fu_160_p4;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_CS_fsm_state14, ap_phi_mux_phi_ln405_3_phi_fu_178_p4, ap_return_4_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_return_4 <= ap_phi_mux_phi_ln405_3_phi_fu_178_p4;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;

    ashr_ln400_fu_562_p2 <= std_logic_vector(shift_right(signed(si00_sc_fu_532_p4),to_integer(unsigned('0' & zext_ln359_reg_639(26-1 downto 0)))));
    ashr_ln401_fu_568_p2 <= std_logic_vector(shift_right(signed(si01_sc_fu_542_p4),to_integer(unsigned('0' & zext_ln359_reg_639(26-1 downto 0)))));
    ashr_ln403_fu_575_p2 <= std_logic_vector(shift_right(signed(si11_sc_fu_552_p4),to_integer(unsigned('0' & zext_ln359_reg_639(26-1 downto 0)))));
    det_mul_raw_fu_453_p2 <= std_logic_vector(unsigned(grp_fu_15620_p_dout0) - unsigned(grp_fu_15624_p_dout0));
    det_raw_fu_459_p4 <= det_mul_raw_fu_453_p2(39 downto 14);
    grp_fp_recip_fu_3707_p_din1 <= det_raw_reg_677;
    grp_fu_15620_p_ce <= ap_const_logic_1;
    grp_fu_15620_p_din0 <= sext_ln156_34_fu_437_p1(26 - 1 downto 0);
    grp_fu_15620_p_din1 <= sext_ln156_36_fu_442_p1(26 - 1 downto 0);
    grp_fu_15624_p_ce <= ap_const_logic_1;
    grp_fu_15624_p_din0 <= sext_ln156_37_fu_447_p1(26 - 1 downto 0);
    grp_fu_15624_p_din1 <= sext_ln156_37_fu_447_p1(26 - 1 downto 0);
    grp_fu_507_p0 <= sext_ln156_38_fu_503_p1(17 - 1 downto 0);
    grp_fu_507_p1 <= sext_ln156_35_reg_711(26 - 1 downto 0);
    grp_fu_521_p0 <= sext_ln156_38_fu_503_p1(17 - 1 downto 0);
    grp_fu_527_p0 <= sext_ln156_38_fu_503_p1(17 - 1 downto 0);
    grp_fu_527_p1 <= sext_ln156_reg_706(26 - 1 downto 0);
    icmp_ln344_fu_265_p2 <= "1" when (unsigned(t_2_fu_257_p3) > unsigned(max_abs_2_fu_231_p3)) else "0";
    icmp_ln354_fu_305_p2 <= "1" when (unsigned(t_5_fu_297_p3) > unsigned(max_abs_3_fu_271_p3)) else "0";
    icmp_ln383_1_fu_485_p2 <= "1" when (signed(tmp_55_fu_475_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln383_fu_469_p2 <= "1" when (signed(det_raw_fu_459_p4) > signed(ap_const_lv26_3FFFFFC)) else "0";
    max_abs_1_fu_221_p1 <= p_read(25 - 1 downto 0);
    max_abs_2_fu_231_p3 <= 
        max_abs_fu_225_p2 when (tmp_fu_213_p3(0) = '1') else 
        max_abs_1_fu_221_p1;
    max_abs_3_fu_271_p3 <= 
        t_2_fu_257_p3 when (icmp_ln344_fu_265_p2(0) = '1') else 
        max_abs_2_fu_231_p3;
    max_abs_4_fu_311_p3 <= 
        t_5_fu_297_p3 when (icmp_ln354_fu_305_p2(0) = '1') else 
        max_abs_3_fu_271_p3;
    max_abs_fu_225_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(max_abs_1_fu_221_p1));
    or_ln362_fu_367_p2 <= (tmp_52_fu_327_p3 or tmp_51_fu_319_p3);
    s00_sc_fu_422_p2 <= std_logic_vector(shift_right(signed(p_read),to_integer(unsigned('0' & zext_ln359_fu_419_p1(26-1 downto 0)))));
    s01_sc_fu_427_p2 <= std_logic_vector(shift_right(signed(p_read1),to_integer(unsigned('0' & zext_ln359_fu_419_p1(26-1 downto 0)))));
    s11_sc_fu_432_p2 <= std_logic_vector(shift_right(signed(p_read3),to_integer(unsigned('0' & zext_ln359_fu_419_p1(26-1 downto 0)))));
    scale_shift_fu_395_p10 <= ((tmp_51_fu_319_p3 & and_ln362_fu_361_p2) & and_ln362_1_fu_379_p2);
    scale_shift_fu_395_p8 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_54_fu_343_p3),3));
    scale_shift_fu_395_p9 <= "XXX";
    select_ln405_fu_581_p3 <= 
        ap_const_lv32_FFFFFFFF when (ap_phi_mux_retval_0_phi_fu_188_p4(0) = '1') else 
        ap_const_lv32_0;
        sext_ln156_34_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s00_sc_fu_422_p2),40));

        sext_ln156_35_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s11_sc_reg_656),43));

        sext_ln156_36_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s11_sc_fu_432_p2),40));

        sext_ln156_37_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s01_sc_fu_427_p2),40));

        sext_ln156_38_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fp_recip_fu_3707_p_dout0),43));

        sext_ln156_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s00_sc_reg_646),43));

    si00_sc_fu_532_p4 <= grp_fu_507_p2(39 downto 14);
    si01_sc_fu_542_p4 <= grp_fu_521_p2(39 downto 14);
    si11_sc_fu_552_p4 <= grp_fu_527_p2(39 downto 14);
    t_1_fu_247_p1 <= p_read1(25 - 1 downto 0);
    t_2_fu_257_p3 <= 
        t_fu_251_p2 when (tmp_49_fu_239_p3(0) = '1') else 
        t_1_fu_247_p1;
    t_3_fu_287_p1 <= p_read3(25 - 1 downto 0);
    t_4_fu_291_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(t_3_fu_287_p1));
    t_5_fu_297_p3 <= 
        t_4_fu_291_p2 when (tmp_50_fu_279_p3(0) = '1') else 
        t_3_fu_287_p1;
    t_fu_251_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(t_1_fu_247_p1));
    tmp_49_fu_239_p3 <= p_read1(25 downto 25);
    tmp_50_fu_279_p3 <= p_read3(25 downto 25);
    tmp_51_fu_319_p3 <= max_abs_4_fu_311_p3(24 downto 24);
    tmp_52_fu_327_p3 <= max_abs_4_fu_311_p3(23 downto 23);
    tmp_53_fu_335_p3 <= max_abs_4_fu_311_p3(22 downto 22);
    tmp_54_fu_343_p3 <= max_abs_4_fu_311_p3(21 downto 21);
    tmp_55_fu_475_p4 <= det_mul_raw_fu_453_p2(39 downto 16);
    tmp_fu_213_p3 <= p_read(25 downto 25);
    xor_ln362_1_fu_373_p2 <= (or_ln362_fu_367_p2 xor ap_const_lv1_1);
    xor_ln362_fu_355_p2 <= (tmp_51_fu_319_p3 xor ap_const_lv1_1);
    zext_ln359_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(scale_shift_reg_634),26));
end behav;
