// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mpc_fpga_top_opencl_mpc_persist_writeback_hls (
        ap_ready,
        prev_steer_rate,
        prev_accel,
        prev_curvature,
        p_anonymous_namespace_g_core_state_persist_prev_steer_rate,
        p_anonymous_namespace_g_core_state_persist_prev_steer_rate_ap_vld,
        p_anonymous_namespace_g_core_state_persist_prev_accel,
        p_anonymous_namespace_g_core_state_persist_prev_accel_ap_vld,
        p_anonymous_namespace_g_core_state_persist_prev_curvature,
        p_anonymous_namespace_g_core_state_persist_prev_curvature_ap_vld,
        p_anonymous_namespace_g_core_state_persist_prev_model_signature,
        p_anonymous_namespace_g_core_state_persist_prev_model_signature_ap_vld,
        ap_rst
);


output   ap_ready;
input  [31:0] prev_steer_rate;
input  [21:0] prev_accel;
input  [31:0] prev_curvature;
output  [31:0] p_anonymous_namespace_g_core_state_persist_prev_steer_rate;
output   p_anonymous_namespace_g_core_state_persist_prev_steer_rate_ap_vld;
output  [31:0] p_anonymous_namespace_g_core_state_persist_prev_accel;
output   p_anonymous_namespace_g_core_state_persist_prev_accel_ap_vld;
output  [31:0] p_anonymous_namespace_g_core_state_persist_prev_curvature;
output   p_anonymous_namespace_g_core_state_persist_prev_curvature_ap_vld;
output  [0:0] p_anonymous_namespace_g_core_state_persist_prev_model_signature;
output   p_anonymous_namespace_g_core_state_persist_prev_model_signature_ap_vld;
input   ap_rst;

assign ap_ready = 1'b1;

assign p_anonymous_namespace_g_core_state_persist_prev_accel = $signed(prev_accel);

assign p_anonymous_namespace_g_core_state_persist_prev_accel_ap_vld = 1'b1;

assign p_anonymous_namespace_g_core_state_persist_prev_curvature = prev_curvature;

assign p_anonymous_namespace_g_core_state_persist_prev_curvature_ap_vld = 1'b1;

assign p_anonymous_namespace_g_core_state_persist_prev_model_signature = 1'd1;

assign p_anonymous_namespace_g_core_state_persist_prev_model_signature_ap_vld = 1'b1;

assign p_anonymous_namespace_g_core_state_persist_prev_steer_rate = prev_steer_rate;

assign p_anonymous_namespace_g_core_state_persist_prev_steer_rate_ap_vld = 1'b1;

endmodule //mpc_fpga_top_opencl_mpc_persist_writeback_hls
