// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mpc_fpga_top_opencl_fp_atan_lut_fn (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [20:0] x;
output  [20:0] ap_return;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] atan_lut_fn_q0;
wire   [0:0] neg_fu_97_p3;
reg   [0:0] neg_reg_274;
wire   [9:0] idx_1_fu_171_p3;
reg   [9:0] idx_1_reg_279;
wire   [20:0] frac_raw_fu_196_p2;
reg  signed [20:0] frac_raw_reg_284;
reg   [12:0] value_reg_294;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln649_fu_179_p1;
wire   [63:0] zext_ln651_fu_211_p1;
reg    atan_lut_fn_ce0_local;
reg   [10:0] atan_lut_fn_address0_local;
wire   [20:0] abs_x_fu_105_p2;
wire   [20:0] abs_x_2_fu_111_p3;
wire   [0:0] tmp_fu_135_p3;
wire   [14:0] trunc_ln642_1_fu_125_p4;
wire   [14:0] idx_fu_143_p3;
wire   [4:0] tmp_105_fu_155_p4;
wire   [0:0] icmp_ln645_fu_165_p2;
wire   [9:0] trunc_ln642_fu_151_p1;
wire   [8:0] trunc_ln649_fu_184_p1;
wire   [20:0] scaled_fu_119_p2;
wire   [20:0] shl_ln_fu_188_p3;
wire   [10:0] zext_ln642_fu_202_p1;
wire   [10:0] add_ln651_fu_205_p2;
wire   [13:0] zext_ln759_4_fu_219_p1;
wire   [13:0] zext_ln759_3_fu_216_p1;
wire  signed [13:0] dv_raw_fu_223_p2;
wire    ap_CS_fsm_state5;
wire   [34:0] grp_fu_236_p2;
wire   [20:0] zext_ln759_fu_242_p1;
wire   [20:0] interp_raw_fu_245_p4;
wire   [20:0] raw_33_fu_255_p2;
wire   [20:0] raw_fu_261_p2;
reg    grp_fu_236_ce;
wire    ap_CS_fsm_state4;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

mpc_fpga_top_opencl_fp_atan_lut_fn_atan_lut_fn_ROM_2P_BRAM_1R #(
    .DataWidth( 13 ),
    .AddressRange( 1025 ),
    .AddressWidth( 11 ))
atan_lut_fn_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(atan_lut_fn_address0_local),
    .ce0(atan_lut_fn_ce0_local),
    .q0(atan_lut_fn_q0)
);

mpc_fpga_top_opencl_mul_21s_14s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 35 ))
mul_21s_14s_35_3_1_U329(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(frac_raw_reg_284),
    .din1(dv_raw_fu_223_p2),
    .ce(grp_fu_236_ce),
    .dout(grp_fu_236_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        frac_raw_reg_284 <= frac_raw_fu_196_p2;
        idx_1_reg_279 <= idx_1_fu_171_p3;
        neg_reg_274 <= x[32'd20];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        value_reg_294 <= atan_lut_fn_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_ce) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        atan_lut_fn_address0_local = zext_ln651_fu_211_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        atan_lut_fn_address0_local = zext_ln649_fu_179_p1;
    end else begin
        atan_lut_fn_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        atan_lut_fn_ce0_local = 1'b1;
    end else begin
        atan_lut_fn_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_ce) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_236_ce = 1'b0;
    end else begin
        grp_fu_236_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_x_2_fu_111_p3 = ((neg_fu_97_p3[0:0] == 1'b1) ? abs_x_fu_105_p2 : x);

assign abs_x_fu_105_p2 = (21'd0 - x);

assign add_ln651_fu_205_p2 = (zext_ln642_fu_202_p1 + 11'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return = ((neg_reg_274[0:0] == 1'b1) ? raw_fu_261_p2 : raw_33_fu_255_p2);

assign dv_raw_fu_223_p2 = (zext_ln759_4_fu_219_p1 - zext_ln759_3_fu_216_p1);

assign frac_raw_fu_196_p2 = (scaled_fu_119_p2 - shl_ln_fu_188_p3);

assign icmp_ln645_fu_165_p2 = ((tmp_105_fu_155_p4 != 5'd0) ? 1'b1 : 1'b0);

assign idx_1_fu_171_p3 = ((icmp_ln645_fu_165_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln642_fu_151_p1);

assign idx_fu_143_p3 = ((tmp_fu_135_p3[0:0] == 1'b1) ? 15'd0 : trunc_ln642_1_fu_125_p4);

assign interp_raw_fu_245_p4 = {{grp_fu_236_p2[32:12]}};

assign neg_fu_97_p3 = x[32'd20];

assign raw_33_fu_255_p2 = (zext_ln759_fu_242_p1 + interp_raw_fu_245_p4);

assign raw_fu_261_p2 = (21'd0 - raw_33_fu_255_p2);

assign scaled_fu_119_p2 = abs_x_2_fu_111_p3 << 21'd7;

assign shl_ln_fu_188_p3 = {{trunc_ln649_fu_184_p1}, {12'd0}};

assign tmp_105_fu_155_p4 = {{idx_fu_143_p3[14:10]}};

assign tmp_fu_135_p3 = abs_x_2_fu_111_p3[32'd20];

assign trunc_ln642_1_fu_125_p4 = {{abs_x_2_fu_111_p3[19:5]}};

assign trunc_ln642_fu_151_p1 = idx_fu_143_p3[9:0];

assign trunc_ln649_fu_184_p1 = idx_1_fu_171_p3[8:0];

assign zext_ln642_fu_202_p1 = idx_1_reg_279;

assign zext_ln649_fu_179_p1 = idx_1_fu_171_p3;

assign zext_ln651_fu_211_p1 = add_ln651_fu_205_p2;

assign zext_ln759_3_fu_216_p1 = value_reg_294;

assign zext_ln759_4_fu_219_p1 = atan_lut_fn_q0;

assign zext_ln759_fu_242_p1 = value_reg_294;

endmodule //mpc_fpga_top_opencl_fp_atan_lut_fn
