// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mpc_fpga_top_opencl_mpc_compute_hls_Pipeline_VITIS_LOOP_1183_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_x_7_address1,
        y_x_7_ce1,
        y_x_7_we1,
        y_x_7_d1,
        y_x_6_address1,
        y_x_6_ce1,
        y_x_6_we1,
        y_x_6_d1,
        y_x_5_address1,
        y_x_5_ce1,
        y_x_5_we1,
        y_x_5_d1,
        y_x_4_address1,
        y_x_4_ce1,
        y_x_4_we1,
        y_x_4_d1,
        y_x_3_address1,
        y_x_3_ce1,
        y_x_3_we1,
        y_x_3_d1,
        y_x_2_address1,
        y_x_2_ce1,
        y_x_2_we1,
        y_x_2_d1,
        y_x_1_address1,
        y_x_1_ce1,
        y_x_1_we1,
        y_x_1_d1,
        y_x_address1,
        y_x_ce1,
        y_x_we1,
        y_x_d1,
        z_x_7_address1,
        z_x_7_ce1,
        z_x_7_we1,
        z_x_7_d1,
        z_x_6_address1,
        z_x_6_ce1,
        z_x_6_we1,
        z_x_6_d1,
        z_x_5_address1,
        z_x_5_ce1,
        z_x_5_we1,
        z_x_5_d1,
        z_x_4_address1,
        z_x_4_ce1,
        z_x_4_we1,
        z_x_4_d1,
        z_x_3_address1,
        z_x_3_ce1,
        z_x_3_we1,
        z_x_3_d1,
        z_x_2_address1,
        z_x_2_ce1,
        z_x_2_we1,
        z_x_2_d1,
        z_x_1_address1,
        z_x_1_ce1,
        z_x_1_we1,
        z_x_1_d1,
        z_x_address1,
        z_x_ce1,
        z_x_we1,
        z_x_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] y_x_7_address1;
output   y_x_7_ce1;
output   y_x_7_we1;
output  [31:0] y_x_7_d1;
output  [4:0] y_x_6_address1;
output   y_x_6_ce1;
output   y_x_6_we1;
output  [31:0] y_x_6_d1;
output  [4:0] y_x_5_address1;
output   y_x_5_ce1;
output   y_x_5_we1;
output  [31:0] y_x_5_d1;
output  [4:0] y_x_4_address1;
output   y_x_4_ce1;
output   y_x_4_we1;
output  [31:0] y_x_4_d1;
output  [4:0] y_x_3_address1;
output   y_x_3_ce1;
output   y_x_3_we1;
output  [31:0] y_x_3_d1;
output  [4:0] y_x_2_address1;
output   y_x_2_ce1;
output   y_x_2_we1;
output  [31:0] y_x_2_d1;
output  [4:0] y_x_1_address1;
output   y_x_1_ce1;
output   y_x_1_we1;
output  [31:0] y_x_1_d1;
output  [4:0] y_x_address1;
output   y_x_ce1;
output   y_x_we1;
output  [31:0] y_x_d1;
output  [4:0] z_x_7_address1;
output   z_x_7_ce1;
output   z_x_7_we1;
output  [31:0] z_x_7_d1;
output  [4:0] z_x_6_address1;
output   z_x_6_ce1;
output   z_x_6_we1;
output  [31:0] z_x_6_d1;
output  [4:0] z_x_5_address1;
output   z_x_5_ce1;
output   z_x_5_we1;
output  [31:0] z_x_5_d1;
output  [4:0] z_x_4_address1;
output   z_x_4_ce1;
output   z_x_4_we1;
output  [31:0] z_x_4_d1;
output  [4:0] z_x_3_address1;
output   z_x_3_ce1;
output   z_x_3_we1;
output  [31:0] z_x_3_d1;
output  [4:0] z_x_2_address1;
output   z_x_2_ce1;
output   z_x_2_we1;
output  [31:0] z_x_2_d1;
output  [4:0] z_x_1_address1;
output   z_x_1_ce1;
output   z_x_1_we1;
output  [31:0] z_x_1_d1;
output  [4:0] z_x_address1;
output   z_x_ce1;
output   z_x_we1;
output  [31:0] z_x_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln1183_fu_368_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln1183_fu_380_p1;
reg   [4:0] k_4_fu_68;
wire   [4:0] add_ln1183_fu_374_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_k;
reg    z_x_we1_local;
reg    z_x_ce1_local;
reg    z_x_1_we1_local;
reg    z_x_1_ce1_local;
reg    z_x_2_we1_local;
reg    z_x_2_ce1_local;
reg    z_x_3_we1_local;
reg    z_x_3_ce1_local;
reg    z_x_4_we1_local;
reg    z_x_4_ce1_local;
reg    z_x_5_we1_local;
reg    z_x_5_ce1_local;
reg    z_x_6_we1_local;
reg    z_x_6_ce1_local;
reg    z_x_7_we1_local;
reg    z_x_7_ce1_local;
reg    y_x_we1_local;
reg    y_x_ce1_local;
reg    y_x_1_we1_local;
reg    y_x_1_ce1_local;
reg    y_x_2_we1_local;
reg    y_x_2_ce1_local;
reg    y_x_3_we1_local;
reg    y_x_3_ce1_local;
reg    y_x_4_we1_local;
reg    y_x_4_ce1_local;
reg    y_x_5_we1_local;
reg    y_x_5_ce1_local;
reg    y_x_6_we1_local;
reg    y_x_6_ce1_local;
reg    y_x_7_we1_local;
reg    y_x_7_ce1_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 k_4_fu_68 = 5'd0;
#0 ap_done_reg = 1'b0;
end

mpc_fpga_top_opencl_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln1183_fu_368_p2 == 1'd0)) begin
            k_4_fu_68 <= add_ln1183_fu_374_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_4_fu_68 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k = 5'd0;
    end else begin
        ap_sig_allocacmp_k = k_4_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_1_ce1_local = 1'b1;
    end else begin
        y_x_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_1_we1_local = 1'b1;
    end else begin
        y_x_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_2_ce1_local = 1'b1;
    end else begin
        y_x_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_2_we1_local = 1'b1;
    end else begin
        y_x_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_3_ce1_local = 1'b1;
    end else begin
        y_x_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_3_we1_local = 1'b1;
    end else begin
        y_x_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_4_ce1_local = 1'b1;
    end else begin
        y_x_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_4_we1_local = 1'b1;
    end else begin
        y_x_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_5_ce1_local = 1'b1;
    end else begin
        y_x_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_5_we1_local = 1'b1;
    end else begin
        y_x_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_6_ce1_local = 1'b1;
    end else begin
        y_x_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_6_we1_local = 1'b1;
    end else begin
        y_x_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_7_ce1_local = 1'b1;
    end else begin
        y_x_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_7_we1_local = 1'b1;
    end else begin
        y_x_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_ce1_local = 1'b1;
    end else begin
        y_x_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        y_x_we1_local = 1'b1;
    end else begin
        y_x_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_1_ce1_local = 1'b1;
    end else begin
        z_x_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_1_we1_local = 1'b1;
    end else begin
        z_x_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_2_ce1_local = 1'b1;
    end else begin
        z_x_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_2_we1_local = 1'b1;
    end else begin
        z_x_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_3_ce1_local = 1'b1;
    end else begin
        z_x_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_3_we1_local = 1'b1;
    end else begin
        z_x_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_4_ce1_local = 1'b1;
    end else begin
        z_x_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_4_we1_local = 1'b1;
    end else begin
        z_x_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_5_ce1_local = 1'b1;
    end else begin
        z_x_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_5_we1_local = 1'b1;
    end else begin
        z_x_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_6_ce1_local = 1'b1;
    end else begin
        z_x_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_6_we1_local = 1'b1;
    end else begin
        z_x_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_7_ce1_local = 1'b1;
    end else begin
        z_x_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_7_we1_local = 1'b1;
    end else begin
        z_x_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_ce1_local = 1'b1;
    end else begin
        z_x_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1183_fu_368_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        z_x_we1_local = 1'b1;
    end else begin
        z_x_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1183_fu_374_p2 = (ap_sig_allocacmp_k + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln1183_fu_368_p2 = ((ap_sig_allocacmp_k == 5'd20) ? 1'b1 : 1'b0);

assign y_x_1_address1 = zext_ln1183_fu_380_p1;

assign y_x_1_ce1 = y_x_1_ce1_local;

assign y_x_1_d1 = 32'd0;

assign y_x_1_we1 = y_x_1_we1_local;

assign y_x_2_address1 = zext_ln1183_fu_380_p1;

assign y_x_2_ce1 = y_x_2_ce1_local;

assign y_x_2_d1 = 32'd0;

assign y_x_2_we1 = y_x_2_we1_local;

assign y_x_3_address1 = zext_ln1183_fu_380_p1;

assign y_x_3_ce1 = y_x_3_ce1_local;

assign y_x_3_d1 = 32'd0;

assign y_x_3_we1 = y_x_3_we1_local;

assign y_x_4_address1 = zext_ln1183_fu_380_p1;

assign y_x_4_ce1 = y_x_4_ce1_local;

assign y_x_4_d1 = 32'd0;

assign y_x_4_we1 = y_x_4_we1_local;

assign y_x_5_address1 = zext_ln1183_fu_380_p1;

assign y_x_5_ce1 = y_x_5_ce1_local;

assign y_x_5_d1 = 32'd0;

assign y_x_5_we1 = y_x_5_we1_local;

assign y_x_6_address1 = zext_ln1183_fu_380_p1;

assign y_x_6_ce1 = y_x_6_ce1_local;

assign y_x_6_d1 = 32'd0;

assign y_x_6_we1 = y_x_6_we1_local;

assign y_x_7_address1 = zext_ln1183_fu_380_p1;

assign y_x_7_ce1 = y_x_7_ce1_local;

assign y_x_7_d1 = 32'd0;

assign y_x_7_we1 = y_x_7_we1_local;

assign y_x_address1 = zext_ln1183_fu_380_p1;

assign y_x_ce1 = y_x_ce1_local;

assign y_x_d1 = 32'd0;

assign y_x_we1 = y_x_we1_local;

assign z_x_1_address1 = zext_ln1183_fu_380_p1;

assign z_x_1_ce1 = z_x_1_ce1_local;

assign z_x_1_d1 = 32'd0;

assign z_x_1_we1 = z_x_1_we1_local;

assign z_x_2_address1 = zext_ln1183_fu_380_p1;

assign z_x_2_ce1 = z_x_2_ce1_local;

assign z_x_2_d1 = 32'd0;

assign z_x_2_we1 = z_x_2_we1_local;

assign z_x_3_address1 = zext_ln1183_fu_380_p1;

assign z_x_3_ce1 = z_x_3_ce1_local;

assign z_x_3_d1 = 32'd0;

assign z_x_3_we1 = z_x_3_we1_local;

assign z_x_4_address1 = zext_ln1183_fu_380_p1;

assign z_x_4_ce1 = z_x_4_ce1_local;

assign z_x_4_d1 = 32'd0;

assign z_x_4_we1 = z_x_4_we1_local;

assign z_x_5_address1 = zext_ln1183_fu_380_p1;

assign z_x_5_ce1 = z_x_5_ce1_local;

assign z_x_5_d1 = 32'd0;

assign z_x_5_we1 = z_x_5_we1_local;

assign z_x_6_address1 = zext_ln1183_fu_380_p1;

assign z_x_6_ce1 = z_x_6_ce1_local;

assign z_x_6_d1 = 32'd0;

assign z_x_6_we1 = z_x_6_we1_local;

assign z_x_7_address1 = zext_ln1183_fu_380_p1;

assign z_x_7_ce1 = z_x_7_ce1_local;

assign z_x_7_d1 = 32'd0;

assign z_x_7_we1 = z_x_7_we1_local;

assign z_x_address1 = zext_ln1183_fu_380_p1;

assign z_x_ce1 = z_x_ce1_local;

assign z_x_d1 = 32'd0;

assign z_x_we1 = z_x_we1_local;

assign zext_ln1183_fu_380_p1 = ap_sig_allocacmp_k;

endmodule //mpc_fpga_top_opencl_mpc_compute_hls_Pipeline_VITIS_LOOP_1183_1
