// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mpc_fpga_top_opencl_fp_frenet_recip (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        kappa,
        ey,
        ap_return
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [20:0] kappa;
input  [20:0] ey;
output  [19:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [20:0] denom_2_fu_93_p2;
reg   [20:0] denom_2_reg_171;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_fu_99_p3;
reg   [0:0] tmp_reg_176;
wire   [0:0] icmp_ln73_fu_141_p2;
reg   [0:0] icmp_ln73_reg_181;
wire    ap_CS_fsm_state4;
wire   [20:0] grp_fp_recip_fn_fu_62_x;
wire   [19:0] grp_fp_recip_fn_fu_62_ap_return;
reg    grp_fp_recip_fn_fu_62_ap_ce;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state2;
wire   [41:0] grp_fu_69_p2;
wire   [20:0] product_q_fu_83_p4;
wire   [20:0] sub_ln380_fu_107_p2;
wire   [18:0] tmp_103_fu_113_p4;
wire   [18:0] tmp_104_fu_123_p4;
wire   [18:0] select_ln380_fu_133_p3;
wire   [20:0] select_ln73_fu_147_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
end

mpc_fpga_top_opencl_fp_recip_fn grp_fp_recip_fn_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(grp_fp_recip_fn_fu_62_x),
    .ap_return(grp_fp_recip_fn_fu_62_ap_return),
    .ap_ce(grp_fp_recip_fn_fu_62_ap_ce)
);

mpc_fpga_top_opencl_mul_21s_21s_42_3_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 42 ))
mul_21s_21s_42_3_1_x_U402(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ey),
    .din1(kappa),
    .ce(1'b1),
    .dout(grp_fu_69_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        denom_2_reg_171 <= denom_2_fu_93_p2;
        icmp_ln73_reg_181 <= icmp_ln73_fu_141_p2;
        tmp_reg_176 <= denom_2_fu_93_p2[32'd20];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state1))) begin
        grp_fp_recip_fn_fu_62_ap_ce = 1'b0;
    end else begin
        grp_fp_recip_fn_fu_62_ap_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_return = grp_fp_recip_fn_fu_62_ap_return;

assign denom_2_fu_93_p2 = (21'd4096 - product_q_fu_83_p4);

assign grp_fp_recip_fn_fu_62_x = ((icmp_ln73_reg_181[0:0] == 1'b1) ? select_ln73_fu_147_p3 : denom_2_reg_171);

assign icmp_ln73_fu_141_p2 = (($signed(select_ln380_fu_133_p3) < $signed(19'd1)) ? 1'b1 : 1'b0);

assign product_q_fu_83_p4 = {{grp_fu_69_p2[32:12]}};

assign select_ln380_fu_133_p3 = ((tmp_fu_99_p3[0:0] == 1'b1) ? tmp_103_fu_113_p4 : tmp_104_fu_123_p4);

assign select_ln73_fu_147_p3 = ((tmp_reg_176[0:0] == 1'b1) ? 21'd2097148 : 21'd4);

assign sub_ln380_fu_107_p2 = (21'd0 - denom_2_fu_93_p2);

assign tmp_103_fu_113_p4 = {{sub_ln380_fu_107_p2[20:2]}};

assign tmp_104_fu_123_p4 = {{denom_2_fu_93_p2[20:2]}};

assign tmp_fu_99_p3 = denom_2_fu_93_p2[32'd20];

endmodule //mpc_fpga_top_opencl_fp_frenet_recip
